#### 복습

In [6]:
class Sports:
    def __init__(self, name, player):
        self.name = name
        self.players = player

In [10]:
soccer = Sports("축구", 11)

In [15]:
soccer.name

'축구'

In [41]:
class Sports:
    def __init__(self, name, player):
        self.name = name
        self.players = player
        
    def explain(self):
        print(f"{self.name}은(는) 한 팀당 {self.players}명이 하는 스포츠 입니다")

In [42]:
soccer = Sports("축구", 11)

In [43]:
soccer.explain()

축구은(는) 한 팀당 11명이 하는 스포츠 입니다


In [31]:
class Plant:
    def __init__(self, name):
        self.name = name
        
    def color(self):
        self.color = "green"
        return self.color

In [32]:
소나무 = Plant("소나무")

In [33]:
소나무.color()

'green'

In [37]:
class Apple(Plant):
    def color(self):
        self.color = "Red"
        return self.color

In [44]:
사과 = Apple("홍옥")

In [45]:
사과.color()

'Red'

In [48]:
f = open("new.txt", 'w')
for _ in range(10):
    f.write("Hello\n")
f.close()

In [49]:
f = open("new.txt", 'r')
data = f.readlines()
print(data)
f.close()

['Hello\n', 'Hello\n', 'Hello\n', 'Hello\n', 'Hello\n', 'Hello\n', 'Hello\n', 'Hello\n', 'Hello\n', 'Hello\n']


In [51]:
f = open("new.txt", 'r')
data = f.readlines()
for i in data:
    print(i, end = " ")
f.close()

Hello
 Hello
 Hello
 Hello
 Hello
 Hello
 Hello
 Hello
 Hello
 Hello
 

In [53]:
f = open("new.txt", 'r')
data = f.read()
print(data)
f.close()

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello



In [54]:
f = open("new.txt", 'w')
for _ in range(10):
    f.write("good\n")
f.close()

In [55]:
f = open("new.txt", 'r')
data = f.read()
print(data)
f.close()

good
good
good
good
good
good
good
good
good
good



In [61]:
with open("gugu.txt", 'w') as f:
    for i in range(2, 10):
        for j in range(1, 10):
            f.write(f"{i*j} ")
        f.write("\n")

# 0908

### 클래스 변수

In [71]:
class Family:
    lastname = "박"   #클래스 변수 생성
    
    def __init__(self, name):
        self.name = name   #인스턴스 변수

In [63]:
Family1 = Family("길동")

In [64]:
Family1.name

'길동'

In [65]:
Family1.lastname

'박'

In [66]:
Family.lastname

'박'

In [67]:
Family2 = Family("우치")

In [68]:
Family2.name

'우치'

In [69]:
Family2.lastname

'박'

In [70]:
print(id(Family1.lastname))
print(id(Family2.lastname))

1902481486384
1902481486384


In [76]:
class Family:
    lastname = "박"   #클래스 변수 생성
    
    def __init__(self, name):
        self.name = name   #지역변수(instanse)
    
    def show_name(self):
        print(Family.lastname)
        print(self.lastname)
        print(self.name)

In [77]:
fam1 = Family("길동")

In [78]:
fam1.show_name()

박
박
길동


In [81]:
#클래스 변수는 인스턴스 변수들이 다같이 공유한다

In [82]:
#클래스 바깥에 변수 지정
name = "우영우"   #전역변수(global)

class Family:
    lastname = "박"
    
    def __init__(self, name):
        self.name = name
    
    def show_name(self):
        print(name)    #함수 바깥에 있는 변수라서 공통적으로 보여진다
        print(Family.lastname)
        print(self.lastname)
        print(self.name)

In [83]:
fam1 = Family("길동")
fam1.show_name()

우영우
박
박
길동


In [90]:
name = "IU"

class Person:
    lastname = "Son"
    
    def __init__(self, name):
        self.name = name
        
    def show_name(self):
        print(name)
        print(Person.lastname)
        print(self.name)

In [91]:
a = Person("흥민")
a.show_name()

IU
Son
흥민


### 상속 후 변수 추가
-__init__와 관련있다 (__init__에서 변수를 만들기 때문에)

* 부모 클래스에서 인자로 입력받는 것이 없을 때

In [92]:
class Person:
    def __init__(self):
        self.name = "Lee"
        self.age = 25

In [93]:
class Korean(Person):
    pass

In [94]:
p1 = Person()
p1.name

'Lee'

In [95]:
k1 = Korean()
k1.name

'Lee'

In [96]:
class Korean(Person):
    def __init__(self):
        self.lang = "한국어"

In [97]:
k1 = Korean()
k1.lang

'한국어'

In [98]:
k1.name

AttributeError: 'Korean' object has no attribute 'name'

In [99]:
#부모 클래스와 같은 이름의 메서드(__init__)로 오버라이딩 되어 부모 클래스에 있던 메서드는 실행되지 않음

In [100]:
class Korean(Person):
    def __init__(self):
        super().__init__()   #부모 클래스에 있던 __init__()를 불러옴
        self.lang = "한국어"

In [101]:
k2 = Korean()
print(k2.lang)
print(k2.name)

한국어
Lee


In [106]:
class American(Person):
    def __init__(self):
        super().__init__()
        self.lang = "English"

In [107]:
a1 = American()
a1.lang

'English'

* 부모 클래스에서 인자로 입력받는 것이 있을 때

In [114]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
class Korean(Person):
    def __init__(self, name, age):   #부모 클래스에 있는 변수를 같이 써줘야 함
        super().__init__(name, age)
        self.lang = "한국어"

In [115]:
k1 = Korean("우영우", 32)

In [117]:
print(k1.name)
print(k1.age)

우영우
32


* 자식 클래스에서도 인자를 입력받는 경우

In [123]:
class Korean(Person):
    def __init__(self, name, age, lang):   #모든 변수를 다 써준다 -> 초기화 하면서 세 변수를 모두 다 받아들임
        super().__init__(name, age)
        self.lang = lang

In [119]:
k2 = Korean("우영우", 32, "한국어")

In [121]:
print(k2.name)
print(k2.age)
print(k2.lang)

우영우
32
한국어


## 8. 모듈
-'.py'로 끝나는 파일 을 말한다

## 9. 패키지
-모듈을 모아놓은 것

In [124]:
#under score 2개 -> __ -> double under score -> dunder

In [125]:
import os
os.getcwd()

'C:\\Users\\admin'

In [126]:
os.chdir("C:\\Users\\admin")

In [131]:
os.mkdir("abc")

FileExistsError: [WinError 183] 파일이 이미 있으므로 만들 수 없습니다: 'abc'

In [132]:
os.mkdir("abc/a")

FileExistsError: [WinError 183] 파일이 이미 있으므로 만들 수 없습니다: 'abc/a'

In [129]:
os.mkdir("abc/b")

In [130]:
os.mkdir("abc/c")

In [133]:
import sys
sys.path

['C:\\Users\\admin',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\python310.zip',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\DLLs',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310',
 '',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\win32',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\Pythonwin']

In [136]:
sys.path.append("C:\\Users\\admin\\abc\\a")

In [137]:
sys.path

['C:\\Users\\admin',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\python310.zip',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\DLLs',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310',
 '',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\win32',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\Pythonwin',
 'C:/Users/admin/abc/a',
 'C:\\Users\\admin\\abc\\a']

## 10. 예외 처리
-예외 : exception<br>
-except : ~을 제외하고<br>
-try 1,2,3 except 4,5 : 4,5는 제외하고 1,2,3만 실행해라<br>
-4,5 -> error, 즉 except가 error라고 볼 수 있다<br>
-예외처리는 다른 말로 에러처리<br>
-for문에서 에러가 자주 발생한다

In [138]:
a = ["hello", "good"]
for i in range(3):
    print(a[i])

hello
good


IndexError: list index out of range

In [141]:
a = ["hello", "good"]
try:
    for i in range(3):
        print(a[i])
except:   #에러가 생기면 다음을 실행해라
    print("error 입니다")

hello
good
error 입니다


In [143]:
print(4 / 2)
print(4 / 0)

2.0


ZeroDivisionError: division by zero

In [145]:
try:
    print(4 / 2)
    print(4 / 0)
except ZeroDivisionError as e:
    print(e)    #e : explain
    #print("에러입니다")

2.0
division by zero


In [146]:
a = ["hello", "good"]
for i in range(3):
    print(a[i])

hello
good


IndexError: list index out of range

#### 1. 일반적인 에러처리

In [147]:
a = ["hello", "good"]

try:
    for i in range(3):
        print(a[i])
except:
    print("에러입니다")

hello
good
에러입니다


#### 2. 에러의 종류에 맞는 에러처리

In [149]:
a = ["hello", "good"]

try:
    for i in range(3):
        print(a[i])
except IndexError as e:
    print(e)
    #print("에러입니다")

hello
good
list index out of range


In [150]:
#에러 이름이 안맞다면
a = ["hello", "good"]

try:
    for i in range(3):
        print(a[i])
except ZeroDivisionError as e:
    print(e)
    #print("에러입니다")

hello
good


IndexError: list index out of range

## 11. 내장 함수
-파이썬이 제공해주는 함수, 총 69개<br>
-참고 사이트 : https://docs.python.org/ko/3/library/functions.html#func-range

In [152]:
a = "Hello"
dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [153]:
len(a)

5

* enumerate()

In [154]:
a = ['a','b','c']
for i in a:
    print(i)

a
b
c


In [155]:
a = ['a','b','c']
for i in enumerate(a):
    print(i)

(0, 'a')
(1, 'b')
(2, 'c')


In [157]:
for i, j in enumerate(a):
    print(i, j)

0 a
1 b
2 c


In [158]:
dics = {'a':0, 'b':1, 'c':2}
dics

{'a': 0, 'b': 1, 'c': 2}

* a = ['a','b','c'] 일 때 위의 dics와 같은 딕셔너리 c를 만들어라(enumerate를 사용하여)

In [161]:
a = ['a','b','c']
c = {}

for i, j in enumerate(a):
    c[j] = i
print(c)

{'a': 0, 'b': 1, 'c': 2}


* filter()
```
filter(함수이름, 자료)
```
-들어가는 함수는 참, 거짓을 아웃풋으로 내야한다<br>
-자료 안의 원소 하나하나에 대해 함수를 적용시켜주는 함수
-> map과 같다

In [170]:
a = [1, -3, 2, 0, -5, 6]
print(a > 0)   #'리스트 전체(a)'가 0보다 큰건지 판별하려함 -> 파이썬으로는 할 수 없다

TypeError: '>' not supported between instances of 'list' and 'int'

In [171]:
def positive(a):
    return a > 0   #참, 거짓으로 리턴값이 나온다

positive(-3)

False

In [172]:
a = [1, -3, 2, 0, -5, 6]
filter(positive , a)

In [173]:
a = [1, -3, 2, 0, -5, 6]
list(filter(positive , a))

[1, 2, 6]

In [174]:
#filter에서는 lambda 함수를 많이 사용한다
a = [1, -3, 2, 0, -5, 6]
list(filter(lambda a: a > 0, a))

[1, 2, 6]

In [177]:
#a = [1, -3, 2, 0, -5, 6]
#print(a > 0)

import numpy as np
a = np.array([1, -3, 2, 0, -5, 6])
a   #a는 numpy가 요소마다 작동게끔 되었다

array([ 1, -3,  2,  0, -5,  6])

In [178]:
a > 0

array([ True, False,  True, False, False,  True])

In [179]:
a[a > 0]

array([1, 2, 6])