#### 0915 복습

In [3]:
#1
import re
p = re.compile("[A-z]+")
p.findall("Life is too short")

['Life', 'is', 'too', 'short']

In [4]:
#2
data = '''
이름 : 김철수
전화번호 : 010 - 1234 - 1234
나이 : 30
성별 : 남
'''

p = re.compile("\d+")
p.findall(data)

['010', '1234', '1234', '30']

In [5]:
#3
s = "black blue and brown"
p = re.compile("bl[a-z]+")
p.findall(s)

['black', 'blue']

In [10]:
#4
s = "http://naver.com\nhttp://google.com\nftp://daum.net"

p = re.compile(r".+(?=:)")
p.findall(s)

['http', 'http', 'ftp']

In [16]:
#4
s = "http://naver.com  http://google.com  ftp://daum.net"

p = re.compile(r"\w+(?=:)")
p.findall(s)

['http', 'http', 'ftp']

In [19]:
s = "http://naver.com\nhttp://google.com\nftp://daum.net"

p = re.compile(r"(?<=//).+")
p.findall(s)

['naver.com', 'google.com', 'daum.net']

In [18]:
s = "http://naver.com  http://google.com  ftp://daum.net"

p = re.compile(r"(?<=//)\S+")
p.findall(s)

['naver.com', 'google.com', 'daum.net']

In [14]:
p = re.compile(r"[a-z]+[.][a-z]{3}")
p.findall(s)

['naver.com', 'google.com', 'daum.net']

In [24]:
data = '''
안녕하세요 그리고 그리고
안녕하세요 또 또
안녕하세요 그런데 그런데 
안녕하세요 끝 끝
'''

p = re.compile(r"(?P<repeat>\w+)\s+(?P=repeat)")

for d in p.finditer(data):
    print(d.group())

그리고 그리고
또 또
그런데 그런데
끝 끝


In [38]:
data = '''
안녕하세요 그리고 그리고
안녕하세요 또 또
안녕하세요 그런데 그런데 
안녕하세요 끝 끝
'''

set(re.findall("\w+", data))

{'그런데', '그리고', '끝', '또', '안녕하세요'}

In [39]:
set(re.findall("\w+\S|\w", data))

{'그런데', '그리고', '끝', '또', '안녕하세요'}

### 0916

#### (1)

In [2]:
import urllib.request as req
import re

In [3]:
req.urlopen("http://daum.net")   #urlopen() : url 접속

In [4]:
req.urlopen("http://daum.net").read()   #url 코드를 가져온다

b'<!DOCTYPE html><html lang="ko"> <head> <meta charset="utf-8" /> <title>Daum</title> <meta http-equiv="x-ua-compatible" content="IE=edge" /> <meta property="og:url" content="//www.daum.net/" /> <meta property="og:type" content="website" /> <meta property="og:title" content="Daum" /> <meta http-equiv="Pragma" content="no-cache" /> <meta http-equiv="Expires" content="-1" /> <meta name="referrer" content="origin" /> <meta property="og:image" content="https://i1.daumcdn.net/svc/image/U03/common_icon/5587C4E4012FCD0001" /> <meta property="og:description" content="\xec\x9d\xb4\xec\x9a\xa9\xec\x9e\x90 \xec\x84\xa0\xed\x83\x9d\xea\xb6\x8c\xec\x9d\x84 \xea\xb0\x95\xed\x99\x94\xed\x95\x9c \xeb\x89\xb4\xec\x8a\xa4, \xec\x84\xb8\xec\x83\x81\xec\x9d\x98 \xeb\xaa\xa8\xeb\x93\xa0 \xec\xa0\x95\xeb\xb3\xb4\xeb\xa5\xbc \xec\x97\xb0\xea\xb2\xb0\xed\x95\x98\xeb\x8a\x94 \xea\xb2\x80\xec\x83\x89. Daum\xec\x97\x90\xec\x84\x9c \xeb\x82\x98\xec\x9d\x98 \xea\xb4\x80\xec\x8b\xac \xec\xbd\x98\xed\x85\x90\xec\xb8

In [10]:
data = req.urlopen("http://daum.net").read().decode("utf-8")
data   #data 전체를 '한 문장' 취급한다

'<!DOCTYPE html><html lang="ko"> <head> <meta charset="utf-8" /> <title>Daum</title> <meta http-equiv="x-ua-compatible" content="IE=edge" /> <meta property="og:url" content="//www.daum.net/" /> <meta property="og:type" content="website" /> <meta property="og:title" content="Daum" /> <meta http-equiv="Pragma" content="no-cache" /> <meta http-equiv="Expires" content="-1" /> <meta name="referrer" content="origin" /> <meta property="og:image" content="https://i1.daumcdn.net/svc/image/U03/common_icon/5587C4E4012FCD0001" /> <meta property="og:description" content="이용자 선택권을 강화한 뉴스, 세상의 모든 정보를 연결하는 검색. Daum에서 나의 관심 콘텐츠를 즐겨보세요." /> <meta name="description" content="이용자 선택권을 강화한 뉴스, 세상의 모든 정보를 연결하는 검색. Daum에서 나의 관심 콘텐츠를 즐겨보세요." /> <meta name="msapplication-task" content="name=Daum;action-uri=//www.daum.net/;icon-uri=/favicon.ico" /> <meta name="msapplication-task" content="name=미디어다음;action-uri=//news.daum.net/;icon-uri=/media_favicon.ico" /> <meta name="msapplication-task" content="name=메일;acti

In [11]:
p = re.compile("https://\S+[.]js")
li = p.findall(data)
for i in li:
    print(i)

https://t1.daumcdn.net/kas/static/na.min.js
https://t1.daumcdn.net/tiara/js/v1/tiara.min.js
https://t1.daumcdn.net/top/tiller-pc/lib/1636937121956/polyfill.min.js
https://t1.daumcdn.net/top/tiller-pc/h/production/20220915_111213/index.js
https://t1.daumcdn.net/kas/static/ba.min.js
https://t1.daumcdn.net/top/tiller-pc/1655174491872/tiller-pc-suggest.js


In [12]:
p = re.compile("https[:./\w]*[.]js")
li = p.findall(data)
for i in li:
    print(i)
#[:./\w] : [] 안에 들어가면 메타 문자의 특성을 갖지 않는다 -> ':', '.', '/', '\w' 하나하나로 인식한다

https://t1.daumcdn.net/kas/static/na.min.js
https://t1.daumcdn.net/tiara/js/v1/tiara.min.js
https://t1.daumcdn.net/kas/static/ba.min.js


In [18]:
webp = '''<div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="true" class="M_704" style="display: block;"><span class="WoYOw">이른 아침 문을 여는 빵집입니다. 아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요. 이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다.  가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다.  참고로, 식빵 나오는 시간은 오전11시~12시 입니다. 빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다. </span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요. 그리고 무엇보다 빵이 정말 맛있어요. 제주도에서 원탑입니다!!! 여기보다 두배는 ...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요!!  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡??도 주시고 친절하세요! 인절미빵 강추입니다!  ...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">인절미빵. 먹물치즈빵? 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요! 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">사진을 제대로 못찍엇는데 뒤에 비닐로 싸진 빵들이에요 ㅋㅋㅋ  여기 진짜 촤고에요 보니 동네찐로컬맛집같아요 빵종류도 많고 각 빵마다 시식빵이 있는데 크기가 넘 커서...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">성산 여행하는 동안 두번이나 방문했어요 빵도 특색있고 하나하나 다 맛있고 사장님도 직원분도 친절하시고  커피도 무료로 먹을수 있게 해주시고 살때마다 서비스빵을 주...</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">사장님 너무 친절하시고 빵이 진짜 맛있어요.. 미친 맛,,,,🥹가격이 타 빵집보다 훠얼씬 저렴한데  맛이 훠얼씬 맛있네요,,,??!?! 저희 동네에 있었음 매일 가고싶네요ㅠㅠㅠ …</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">재료를 아끼지 않으세요 눚은시간 방문했는데도 손님들이 꽤 왔어요 마늘바게트에는 소스를 아끼지 않았고 다른빵들도 크림이 듬뿍 들어 있었어요 서비스도 주시고 시식…</span><span class="_3_09q"><svg xmlns="
http://www.w3.org/2000/svg
" viewBox="0 0 12 7" class="_3Dnsh" aria-hidden="true"><path d="M11.47.52a.74.74 0 0 0-1.04 0l-4.4 4.45v.01L1.57.52A.74.74 0 1 0 .53 1.57l5.12 5.08a.5.5 0 0 0 .7 0l5.12-5.08a.74.74 0 0 0 0-1.05z"></path></svg><span class="place_blind">내용 더보기</span></span></a></div>'''

In [38]:
p = re.compile("[가-힣].+[가-힣]")   #한글로 시작해서 한글로 끝나는 것 (중간은 뭐가 있어도 상관없다)
li = p.findall(webp)
li

['이른 아침 문을 여는 빵집입니다. 아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요. 이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다.  가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다.  참고로, 식빵 나오는 시간은 오전11시~12시 입니다. 빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다. </span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요. 그리고 무엇보다 빵이 정말 맛있어요. 제주도에서 원탑입니다!!! 여기보다 두배는',
 '내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요!!  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡??도 주시고 친절하세요! 인절미빵 강추입니다',
 '내용 더보기</span></span></a></div><div class="faZHB"><a href="#" target="_self" role="button" aria-expanded="false" class="M_704" style="display: block;"><span class="WoYOw">인절미빵. 먹물치즈빵? 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요! 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다',
 '내용 더보기</span></s

In [39]:
p = re.compile("[^가-힣0-9\s.~]")
e = p.sub("", webp)
e

'      704   이른 아침 문을 여는 빵집입니다. 아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요. 이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다.  가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다.  참고로 식빵 나오는 시간은 오전11시~12시 입니다. 빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다.       704   우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요. 그리고 무엇보다 빵이 정말 맛있어요. 제주도에서 원탑입니다 여기보다 두배는 ... 309 \n.3.2000\n 0 0 12 7 3  11.47.52.74.74 0 0 01.04 04.4 4.45.011.57.52.74.74 0 1 0 .53 1.575.12 5.08.5.5 0 0 0 .7 05.125.08.74.74 0 0 0 01.05 내용 더보기      704   맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡도 주시고 친절하세요 인절미빵 강추입니다  ... 309 \n.3.2000\n 0 0 12 7 3  11.47.52.74.74 0 0 01.04 04.4 4.45.011.57.52.74.74 0 1 0 .53 1.575.12 5.08.5.5 0 0 0 .7 05.125.08.74.74 0 0 0 01.05 내용 더보기      704   인절미빵. 먹물치즈빵 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다... 309 \n.3.2000\n 0 0 12 7 3  11.47.52.74.74 0 0 01.04 04.4 4.45.011.57.52.74.74 0 1 0 .53 1.575.12 5.08.5.5 0 0 0 .7 05.125.08.74.74 0 0 0 01.05 내용 더보기      704   사진을 제대로 못찍엇는데 뒤

In [40]:
re.sub("/s/d+[.]/d+", "", e)

'      704   이른 아침 문을 여는 빵집입니다. 아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요. 이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다.  가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다.  참고로 식빵 나오는 시간은 오전11시~12시 입니다. 빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다.       704   우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요. 그리고 무엇보다 빵이 정말 맛있어요. 제주도에서 원탑입니다 여기보다 두배는 ... 309 \n.3.2000\n 0 0 12 7 3  11.47.52.74.74 0 0 01.04 04.4 4.45.011.57.52.74.74 0 1 0 .53 1.575.12 5.08.5.5 0 0 0 .7 05.125.08.74.74 0 0 0 01.05 내용 더보기      704   맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡도 주시고 친절하세요 인절미빵 강추입니다  ... 309 \n.3.2000\n 0 0 12 7 3  11.47.52.74.74 0 0 01.04 04.4 4.45.011.57.52.74.74 0 1 0 .53 1.575.12 5.08.5.5 0 0 0 .7 05.125.08.74.74 0 0 0 01.05 내용 더보기      704   인절미빵. 먹물치즈빵 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다... 309 \n.3.2000\n 0 0 12 7 3  11.47.52.74.74 0 0 01.04 04.4 4.45.011.57.52.74.74 0 1 0 .53 1.575.12 5.08.5.5 0 0 0 .7 05.125.08.74.74 0 0 0 01.05 내용 더보기      704   사진을 제대로 못찍엇는데 뒤

In [44]:
p = re.compile("[가-힣\s.~!]+")
li = p.findall(webp)
for i in li:
    if i != '': 
        print(i)

 
 
 
 
 
 
 
 
 
이른 아침 문을 여는 빵집입니다. 아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요. 이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다.  가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다.  참고로
 식빵 나오는 시간은 오전
시~
시 입니다. 빵 가격은 가성비 괜찮은 편이고 맛은 무난합니다. 
 
 
 
 
 
 
 
 
 
우연히 들어갔는데 사장님이 따뜻하고 친절하셔서 제주도 이미지마저 좋게 느껴졌어요. 그리고 무엇보다 빵이 정말 맛있어요. 제주도에서 원탑입니다!!! 여기보다 두배는 ...
 
 


.
.


 
 
 
 
 
 
 
.
.
.
.
 
 
 
.
 
.
 
.
.
.
.
.
.
 
 
 
 .
 
.
.
 
.
.
.
 
 
 
 .
 
.
.
.
.
 
 
 
 
.
 
내용 더보기
 
 
 
 
 
 
 
 
 
맛집검색하다가 스쳐지나갔는데 숙소근처에 있길래 들렸어요!!  시식하는빵도 있고  빵구매하는데 서비스로 흰색찹살떡
도 주시고 친절하세요! 인절미빵 강추입니다!  ...
 
 


.
.


 
 
 
 
 
 
 
.
.
.
.
 
 
 
.
 
.
 
.
.
.
.
.
.
 
 
 
 .
 
.
.
 
.
.
.
 
 
 
 .
 
.
.
.
.
 
 
 
 
.
 
내용 더보기
 
 
 
 
 
 
 
 
 
인절미빵. 먹물치즈빵
 제일 맛있었고 대파빵은 삼겹살을 부르는 꽤 매운 맛이었어요! 빵이 대체로 다~~~~맛있고 친절하십니다 주차는 근처 공영주차장에 하면 됩니다 다...
 
 


.
.


 
 
 
 
 
 
 
.
.
.
.
 
 
 
.
 
.
 
.
.
.
.
.
.
 
 
 
 .
 
.
.
 
.
.
.
 
 
 
 .
 
.
.
.
.
 
 
 
 
.
 
내용 더보기
 
 
 
 
 
 
 
 
 
사진을 제대로 못찍엇는데 뒤에 비닐로 싸진 빵들이에요 
  여기 진짜 촤고에요 보니 동네찐로컬맛집같아요 빵종류도 

#### (2)

* 전화번호 (010-1234-3434) 의 정규 표현식

In [ ]:
"010[-]\d{4}[-]\d{4}"

In [ ]:
"\d{2,3}[-]\d{4}[-]\d{4}"

* 이메일의 정규 표현식

In [ ]:
prince@naver.com
hello@daum.net
morning@company.co.kr

In [ ]:
"[A-z0-9]+@[A-z0-9]+[.][a-z.]+"

In [ ]:
".+@[a-z0-9]+[.][a-z]+"

* 주민번호 (210203-2134576) 의 정규 표현식

In [ ]:
"\d{6}-\d{7}"

In [ ]:
"\d{6}-[1-6]\d{6}"

#### * 컴파일 옵션

#### (3) 전방, 후방 탐색

In [65]:
text1 = '''
http://www.google.com/

https://mail.google.com/

ftp://ftp.google.com/

''' 

In [66]:
#['http:', 'https:', 'ftp:']
p = re.compile(".+:")
p.findall(text1)

['http:', 'https:', 'ftp:']

In [67]:
#['http', 'https', 'ftp']
p = re.compile(".+(?=:)")
p.findall(text1)

['http', 'https', 'ftp']

In [70]:
text2 = '''apple: $50.24
banana: $35.25
pizza: $100
'''

In [77]:
#['50.24', '35.25', '100']
p = re.compile("[$].+")
p.findall(text2)

['$50.24', '$35.25', '$100']

In [78]:
p = re.compile("\$.+")
p.findall(text2)

['$50.24', '$35.25', '$100']

In [79]:
p = re.compile("(?<=[$]).+")
p.findall(text2)

['50.24', '35.25', '100']

In [88]:
text3 = '''<p>이른 아침 문을 여는 빵집입니다</p>
<h1>아침식사로 빵을 사러 가기엔 좋지만 매장안에서 드실 공간은 없어요</h1>
<h5>이 빵집은 특이하게도 물 또는 커피를 무료로 텀블러에 담아갈수 있습니다</h5>
<p>가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다</p>
<p>참고로 식빵 나오는 시간은 오전9시 입니다</p>
'''

In [89]:
#<p> 와 </p> 사이의 글
p = re.compile("(?<=<p>).+(?=</p>)")
p.findall(text3)

['이른 아침 문을 여는 빵집입니다',
 '가볍게 아침을 해결하고자 하는 여행자나 현지인은 들러보면 좋을 장소입니다',
 '참고로 식빵 나오는 시간은 오전9시 입니다']

### Numpy

#### 배열 만들기

In [90]:
import numpy as np

In [99]:
a = np.array([0,1,2,3])   #입력값으로 리스트가 들어간다
a

array([0, 1, 2, 3])

In [100]:
print(a)   #array가 아닌 리스트로 착각할 수 있다

[0 1 2 3]


In [105]:
print(a.shape)
print(a.size)
print(a.dtype)
print(a.ndim)

(4,)
4
int32
1


In [102]:
li = [0,1,2,3]
np.array(li)

array([0, 1, 2, 3])

In [108]:
#8 bit = 1 byte => 64bit = 8byte
a = np.array([0,1,2,3,4.3])
a.dtype

dtype('float64')

In [109]:
a = np.array([0,1,2,3,4.3], dtype = 'int')
a.dtype

dtype('int32')

In [110]:
a

array([0, 1, 2, 3, 4])

In [111]:
a = np.array([0,1,2,3], dtype ='float')
a

array([0., 1., 2., 3.])

In [113]:
a.dtype

dtype('float64')

In [116]:
a = np.array([0,1,2,3], dtype ='float32')
a.dtype

dtype('float32')

In [118]:
a = np.array([0,1,2,3], dtype ='float16')
a.dtype

dtype('float16')

In [117]:
a = np.array([0,1,2,3], dtype ='float8')
a.dtype

TypeError: data type 'float8' not understood

In [121]:
a = np.array([0,1,2,3], dtype ='int8')   #int8 : byte (-128 to 127)
a.dtype

dtype('int8')

#### * python과 numpy 계산속도 비교

In [129]:
#[2,4,6,8] 출력
list1 = [1,2,3,4]
list2 = [1,2,3,4]
list1 + list2

[1, 2, 3, 4, 1, 2, 3, 4]

In [130]:
#python
list1 = [1,2,3,4]
list2 = [1,2,3,4]

list3 = []
for i in range(4):
    list3.append(list1[i] + list2[i])
list3

[2, 4, 6, 8]

In [131]:
#numpy
array1 = np.array([1,2,3,4])
array2 = np.array([1,2,3,4])

array3 = array1 + array2
array3

array([2, 4, 6, 8])

In [133]:
#일반화_python
def add_list(n):
    li1 = list(range(1, n+1))
    li2 = list(range(1, n+1))
    
    li3 = []
    for i in range(n):
        li3.append(li1[i] + li2[i])
    
    return li3

In [134]:
add_list(10)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [135]:
#일반화_numpy
def add_array(n):
    ar1 = np.array(range(1, n+1))
    ar2 = np.array(range(1, n+1))
    ar3 = ar1 + ar2

    return ar3

In [136]:
add_array(10)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [137]:
def add_list():
    li1 = list(range(1, 101))
    li2 = list(range(1, 101))
    
    li3 = []
    for i in range(100):
        li3.append(li1[i] + li2[i])
    
    return li3

In [139]:
add_list()

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200]

In [141]:
def add_array():
    ar1 = np.array(range(1, 101))
    ar2 = np.array(range(1, 101))
    ar3 = ar1 + ar2

    return ar3

In [142]:
add_array()

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

#### * python과 numpy 계산속도 비교 (2)

In [145]:
import timeit

In [153]:
print(timeit.timeit(add_list, number=10))   #python으로 작동시켰을 때
print(timeit.timeit(add_array, number=10))  #numpy로 작동시켰을 때

0.013877099991077557
0.017169200000353158


In [163]:
li1 = list(range(10000))
li2 = list(range(10000))

In [164]:
def add_list():
    li3 = []
    for i in range(10000):
        li3.append(li1[i] + li2[i])
    
    return li3

In [165]:
print(timeit.timeit(add_list, number=10000))

10.24199119998957


In [166]:
ar1 = np.array(range(10000))
ar2 = np.array(range(10000))

In [167]:
def add_array():
    ar3 = ar1 + ar2

    return ar3

In [168]:
print(timeit.timeit(add_array, number=10000))

0.08365190000040457


### (2) 2차원, 3차원 배열 만들기

#### * 2차원 배열 만들기

In [170]:
np.array([[1,2,3,4], [5,6,7,8]])   #대괄호 2개([[]]) -> 2차원

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [172]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [174]:
np.arange(10).reshape((2, 5))   
#arange(10) -> 1행 10열 (1X10)
#.reshape(2, 5) -> 2행 5열로 변경 (2*5 = 10)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [175]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [178]:
np.arange(12).reshape(3, -1)   #'-1' -> 3이 입력되어있기 때문에 4를 입력하지 않아도 자동으로 처리해준다

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### * 3차원 배열 만들기

In [182]:
np.arange(24).reshape(2,3,4)   #3행 4열이 2장 나온다 (z, y, x)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [181]:
np.arange(24).reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [183]:
np.arange(36).reshape(3, 4, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

### (3) 배열의 연산

#### *elementary wise

In [192]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [193]:
print(a + b)
print(a ** b)

[[ 6  8]
 [10 12]]
[[    1    64]
 [ 2187 65536]]


#### *broadcasting

In [194]:
c = np.array([5, 6])
c

array([5, 6])

In [195]:
a + c

array([[ 6,  8],
       [ 8, 10]])

In [196]:
d = np.array([5])
a + d

array([[6, 7],
       [8, 9]])

In [197]:
a + 6

array([[ 7,  8],
       [ 9, 10]])

In [198]:
e = np.array([5,6,7])
a + e

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [199]:
a = np.array([[1,2,3], [4,5,6]])
c = np.array([5, 6])
a + c

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [203]:
a = np.array([[1,2,3,4], [5,6,7,8]])
c = np.array([5,6])
a + c

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [202]:
a = np.array([[1,2], [3,4], [5,6],[7,8]])
c = np.array([5,6])
a + c

array([[ 6,  8],
       [ 8, 10],
       [10, 12],
       [12, 14]])

In [204]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [209]:
a[4,:]

array([20, 21, 22, 23, 24])

In [210]:
a[:,(1,3)]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [211]:
a[(1,3),(0,2)]

array([ 5, 17])