#### 0916 복습

In [10]:
#1
import re

li=[" ","1","12","123","1234","abc","1a"]

for i in li:
    print(re.sub("[0-9]?", "A", i), end=", ")

A A, AA, AAA, AAAA, AAAAA, AaAbAcA, AAaA, 

In [12]:
#2
import numpy as np

arr = np.arange(1, 101).reshape(10, 10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [16]:
arr[4::3, 3:6:2]

array([[44, 46],
       [74, 76]])

In [17]:
arr[[4, 4, 7, 7], [3, 5, 3, 5]]

array([44, 46, 74, 76])

In [20]:
arr[0, 0]

1

In [21]:
arr[0:4:2, 0:4:2]

array([[ 1,  3],
       [21, 23]])

In [24]:
arr[[0,1], [0,1]]   #[0,0], [1,1] 의 값이 나온다 -> 대각선으로 값을 슬라이싱할 때 좋다

array([ 1, 12])

In [25]:
arr[[0,1,2,3], [6,7,8,9]]

array([ 7, 18, 29, 40])

In [31]:
#3
data = '''
  <head>
    <title>hello world</title>
  </head>
'''

p = re.compile("(?<=<title>).*(?=</title>)")
p.search(data).group()

'hello world'

In [38]:
#4
brr = np.arange(1, 37).reshape(6, 6)
brr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [40]:
brr[:, 1::2]

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30],
       [32, 34, 36]])

In [41]:
brr[:, [1,3,5]]

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30],
       [32, 34, 36]])

In [42]:
brr[:, 0::2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [43]:
brr[:, [0,2,4]]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [47]:
#5
crr = np.arange(1, 100).reshape(3, 3, -1)
crr

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
        [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]],

       [[34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66]],

       [[67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88],
        [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

#### 0919 pdf 문제 풀이

In [48]:
#1.
a = "Hello python! I need python!"
a[-16 : -8]

'! I need'

In [60]:
#3
a="960101-1041111"
a[:6]
a[7:]
print(a[:6] + ", " + a[7:])

960101, 1041111


In [61]:
#4
key='축구:농구:배구:야구'
key.replace(":", "#")

'축구#농구#배구#야구'

In [113]:
#5
a = {"apple" : "사과", "banana" : "바나나" , "cherry" : "체리" }
a["grape"] = "포도"
a

{'apple': '사과', 'banana': '바나나', 'cherry': '체리', 'grape': '포도'}

In [114]:
del a["banana"]
a

{'apple': '사과', 'cherry': '체리', 'grape': '포도'}

In [67]:
#6
result = 0
for i in range(1, 11):
    result += i
print(result)

55


In [103]:
#9
f = lambda x: x*3
f(3)

9

In [80]:
#10
def divide(a, b):
    if a < b:
        a, b = b, a
    
    c = a//b
    d = a%b
    
    return c, d

divide(5, 10)

(2, 0)

In [82]:
#11
numbers = [1,2,3,4,5]
a = []
for n in numbers:
    if n%2 ==1:
        a.append(n*2)
print(a)

[2, 6, 10]


In [119]:
numbers = [1,2,3,4,5]
a = [n*2 for n in numbers if n%2 == 1]
a

[2, 6, 10]

In [83]:
#12
class FirstClass :
    def __init__(self, number):
        self.number = number
    def printNumber(self):
        return self.number
    
a = FirstClass(3)
print(a.printNumber())

3


In [84]:
#13
class Class_A :
    def func_A(self) :
        return 1
class Class_B(Class_A):
    def func_A(self):
        return 2

b = Class_B()
print(b.func_A())

2


In [ ]:
#16
import re
p = re.compile("\d{6}[-][34]\d{6}")

In [87]:
#17
list(filter(lambda x: x < 0,  [1,-2, 3, 5, 8, -3]))

[-2, -3]

In [90]:
lst = []
for i, j in enumerate([1,-2, 3, 5, 8, -3]):
    if j < 0:
        lst.append(j)
print(lst)

[-2, -3]


In [101]:
#18
def fac(n):
    result = 1
    for i in range(1, n+1):
        result = result * i
    
    return result

fac(5)

120

In [121]:
def fac(n):
    if n == 1:
        return 1
    
    return n*fac(n-1)   #재귀함수

fac(5)

120

### 0919

In [122]:
a = np.array([1,2,3,4])
a + np.array([1,2])   #불가능

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [124]:
np.array([[1],[2]])

array([[1],
       [2]])

In [126]:
a + np.array([[1],[2]])   #가능

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

#### Numpy 내장함수를 이용하여 array 만들기<br>
* arange / linspace / zeros / ones / empty / full / tile / **_like

In [2]:
#linspace(start, stop, numbers of element)
import numpy as np
np.linspace(1 ,10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [3]:
np.linspace(1 ,9, 5)

array([1., 3., 5., 7., 9.])

In [152]:
np.linspace(1 ,9, 5, endpoint=False)

array([1. , 2.6, 4.2, 5.8, 7.4])

In [5]:
#np.ones(shape [, dtype, order])
np.ones((2,3))    #(2,3) -> tuple 형태

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.ones((2,3), dtype = "int16")

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [7]:
#np.zeros(shape [, dtype, order])
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
#sparse matrix (희소행렬)
#10x10 = 대부분 0
#3행 3열 부분 1, 5행 6열 부분 1

arr = np.zeros((10, 10))
arr
arr[3,3] = 1
arr[5,6] = 1
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
#모든 원소가 3인 10X10 array
a = np.ones((10, 10))
a*3

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [21]:
np.full((10,10), 3)    #10행 10열 만큼을 3으로 채운다

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [15]:
#단위행렬 - np.identity() 는 정사각행렬이 정해져있다
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
#np.identity(3)과 np.eye(3)은 같다
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(3, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [153]:
a = np.array([0,1,2])
np.tile(a, 2)   #a를 2번 반복
#np.tile(a, (3, 2))   #a를 (3행 2열)번 반복

array([0, 1, 2, 0, 1, 2])

In [23]:
np.empty((2, 3))    #null에 해당하는 주소값, 초기화 안함

array([[1., 0., 0.],
       [1., 0., 0.]])

#### _like() 함수로 배열 만들기<br>
* zeros_like( ) / ones_like( ) / empty_like( ) / full_like( )

In [28]:
#zeros_like() : 형태와 데이터 타입을 유지하면서 '0' 으로 채움
a = np.arange(6).reshape(2,3)
a
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [154]:
b = np.arange(3, dtype = float)
print(b)
b.dtype

[0. 1. 2.]


dtype('float64')

In [31]:
np.zeros_like(b)

array([0., 0., 0.])

In [34]:
#ones_like() : 형태와 데이터 타입을 유지하면서 '1' 으로 채움
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [35]:
np.ones_like(b)

array([1., 1., 1.])

In [36]:
np.empty_like(a)

array([[         0, 1072693248,          0],
       [1072693248,          0, 1072693248]])

In [37]:
np.empty_like(b)

array([1., 1., 1.])

In [40]:
#full_like() : 형태와 데이터 타입을 유지하면서 '입력한 수' 로 채움
np.full_like(a, 3)

array([[3, 3, 3],
       [3, 3, 3]])

In [42]:
np.full_like(b, .31)

array([0.31, 0.31, 0.31])

#### copy 의 두가지 방법<br>
-기본 배열로부터 새로운 배열을 생성하기 위해서는 copy 함수를 이용해 명시적으로 사용해야 한다<br>
-copy 함수로 복사한 배열은 원본 배열과 완전히 다른 '새로운 객체' 이다<br>
-copy( )의 두가지 방법<br>
slice, indexing -> 새로운 객체가 아닌 기존 배열의 뷰 (View : id를 공유하여 본다)<br>
반환한 배열의 값을 변경하면 원본 배열이 변경된다

##### list

In [44]:
a = [1,2,3,4]
b = a
b    #a의 주솟값이 b에 복사됨

[1, 2, 3, 4]

In [153]:
c = a.copy()
c

[1, 2, 3, 4]

In [154]:
import copy
d = copy.copy(a)
d

[1, 2, 3, 4]

In [155]:
b[0] = 100
b

[100, 2, 3, 4]

In [156]:
print(a)
print(c)
print(d)

[100, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]


In [157]:
print(id(a))
print(id(b))
print(id(c))
print(id(d))

2573670481792
2573670481792
2573679587072
2573670240320


##### array

In [158]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [159]:
b = a
b

array([1, 2, 3, 4])

In [160]:
c = a.copy()
c

array([1, 2, 3, 4])

In [161]:
import copy
d = copy.copy(a)
d

array([1, 2, 3, 4])

In [162]:
b[0] = 100
b

array([100,   2,   3,   4])

In [163]:
print(a)
print(c)
print(d)

[100   2   3   4]
[1 2 3 4]
[1 2 3 4]


In [164]:
print(id(a))
print(id(b))
print(id(c))
print(id(d))

2573670808912
2573670808912
2573671044400
2573670793936


In [166]:
np.arange(1, 9, 2)

array([1, 3, 5, 7])

In [167]:
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [168]:
np.ones((3,3), int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### 배열의 결합 : stack<br>
* stack : FILO (first in last out), 선착순의 반대<br>
* hstack / vstack / dstack / concatenate

In [155]:
#[0, 10, 20, 30, 40, 50, 60, 70, 80, 90] 출력
a = np.arange(10)*10
b = np.arange(10)*20
print(a)
print(b)

[ 0 10 20 30 40 50 60 70 80 90]
[  0  20  40  60  80 100 120 140 160 180]


In [156]:
np.vstack((a, b))    #2행 10열

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [  0,  20,  40,  60,  80, 100, 120, 140, 160, 180]])

In [158]:
np.hstack((a, b))    #1행 20열
np.hstack((a, b)).shape

(20,)

In [159]:
a = np.array([[1], [2], [3]])
print(a.shape)
a

(3, 1)


array([[1],
       [2],
       [3]])

In [179]:
b = np.array([[1], [2], [3]])
b

array([[1],
       [2],
       [3]])

In [184]:
np.hstack((a, b))   #[]가 2개 -> 2차원

array([[1, 1],
       [2, 2],
       [3, 3]])

In [185]:
np.dstack((a, b))   #[]가 3개 -> 3차원

array([[[1, 1]],

       [[2, 2]],

       [[3, 3]]])

#### 배열의 분리 : spliting<br>
* 분리한 결과물이 어떻게 나오는지에 따라 -> 수평분리(hsplit) 와 수직분리(vsplit)

In [187]:
a = np.arange(32).reshape(4,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [188]:
np.hsplit(a, 2)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]])]

In [190]:
np.hsplit(a, 4)

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27]]),
 array([[ 4,  5],
        [12, 13],
        [20, 21],
        [28, 29]]),
 array([[ 6,  7],
        [14, 15],
        [22, 23],
        [30, 31]])]

In [189]:
np.vsplit(a, 2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]])]

#### Numpy의 shape 변경 함수<br>
* reshape / flatten / transpose<br>
transpose : 행과 열의 위치를 바꾼다

In [161]:
a = np.arange(32).reshape(4,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [162]:
print(a.shape)    #shape의 아웃풋은 튜플 형태
print(a.size)

(4, 8)
32


In [163]:
a.flatten()     #flatten은 복사해서 출력해 주는 것
#a.flatten().shape    

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [164]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [203]:
a = np.arange(1, 7).reshape(3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [204]:
np.transpose(a)

array([[1, 3, 5],
       [2, 4, 6]])

In [205]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a, b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [208]:
np.vsplit(c, 2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

#### 비교 comparison, 정렬 sort, 인덱싱 indexing

In [49]:
#비교
a = np.array([1,2,3,4])
b = np.array([1,3,4,2])
a == b

array([ True, False, False, False])

In [50]:
a > 2

array([False, False,  True,  True])

In [51]:
a[a>2]

array([3, 4])

In [54]:
#정렬 sort
a = np.array([1,3,4,2])
a

array([1, 3, 4, 2])

In [55]:
np.sort(a)

array([1, 2, 3, 4])

In [56]:
a

array([1, 3, 4, 2])

In [59]:
a.sort()   #.sort() 는 메소드

In [60]:
a

array([1, 2, 3, 4])

In [63]:
a[ : :-1]    #역순으로 정렬

array([4, 3, 2, 1])

In [64]:
a

array([1, 2, 3, 4])

In [165]:
#축을 지정하여 정렬
x = np.array([[2,1,6], [0,7,4], [5,3,2]])
x

array([[2, 1, 6],
       [0, 7, 4],
       [5, 3, 2]])

In [166]:
np.sort(x)

array([[1, 2, 6],
       [0, 4, 7],
       [2, 3, 5]])

In [167]:
print(x)
np.sort(x, axis = 0)    #'axis = 0' : 행은 신경쓰지 않고 '열'을 기준으로만 정렬 (row - wise)

[[2 1 6]
 [0 7 4]
 [5 3 2]]


array([[0, 1, 2],
       [2, 3, 4],
       [5, 7, 6]])

In [71]:
print(x)
np.sort(x, axis = 1)    #'axis = 1' : '행'을 기준으로만 정렬 (coloum - wise)

[[2 1 6]
 [0 7 4]
 [5 3 2]]


array([[1, 2, 6],
       [0, 4, 7],
       [2, 3, 5]])

In [94]:
#인덱싱 indexing : array[행의 인덱스 번호, 열의 인덱스 번호]
a = np.arange(6)
b = np.arange(6) + 10
c = np.arange(6) + 20
d = np.arange(6) + 30
e = np.arange(6) + 40
f = np.arange(6) + 50

np.vstack((a,b,c,d,e,f))

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [80]:
a = np.array([0,1,2,3,4,5])
b = np.array([[0],[10],[20],[30],[40],[50]])
a+b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [81]:
a = np.arange(6)
array = a.copy()
for i in range(5):
    i+=1
    array = np.vstack((array, a+10*i))
array

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [168]:
a = np.arange(100).reshape(10,10)
a = a[0:6:1,0:6:1]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [169]:
#슬라이싱 slicing : var[lower:uppper:step]
#[2, 12, 22, 32, 42, 52]
a[ : , 2]

array([ 2, 12, 22, 32, 42, 52])

In [175]:
#[3, 4]
a[-6, 3:5]

array([3, 4])

In [174]:
#[[44, 45], [54, 55]]
a[4: , 4: ]

array([[44, 45],
       [54, 55]])

In [176]:
#[[20, 22, 24],  [40, 42, 44]]
a[2:5:2, :5:2]

array([[20, 22, 24],
       [40, 42, 44]])

In [177]:
#Fancy indexing
a = np.arange(8)*10
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [178]:
a[[1, 2, -3]]

array([10, 20, 50])

In [180]:
indices = [1, 2, -3]
a[indices]

array([10, 20, 50])

In [105]:
mask = [False, True, True, False, False, True, False, False]
a[mask]

array([10, 20, 50])

In [107]:
mask = np.array([0, 1, 1, 0, 0, 1, 0, 0], dtype = bool)
mask

array([False,  True,  True, False, False,  True, False, False])

In [108]:
a[mask]

array([10, 20, 50])

In [112]:
#2차원 팬시 인덱싱
a = np.arange(100).reshape(10,10)
a = a[0:6:1,0:6:1]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [113]:
[a[0, 1], a[1, 2], a[2, 0], a[2, 3]]

[1, 12, 20, 23]

In [114]:
a[[0,1,2,2], [1,2,0,3]]

array([ 1, 12, 20, 23])

In [115]:
a = np.arange(25).reshape(5,5)
a[[0,1,2,3], [1,2,3,4]]

array([ 1,  7, 13, 19])

#### 수학함수

In [122]:
#sum()
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
sum(a)

array([5, 7, 9])

In [124]:
print(np.sum(a))
print(np.sum(a, axis = 0))
print(np.sum(a, axis = 1))

21
[5 7 9]
[ 6 15]


In [125]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a**b)

[5 7 9]
[  1  32 729]


In [128]:
np.sin(a)   #각각의 요소에 함수 적용

array([0.84147098, 0.90929743, 0.14112001])

In [127]:
np.max(a)

3

In [181]:
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(np.argmin(a))
print(np.argmax(a))

[[1 2 3]
 [4 5 6]]
0
5


In [129]:
#min(), max()
#argmin(), argmax() -> 최소값과 최대값일 때의 x값의 인덱스를 출력해줌

#### np.where()<br>
ifelse의 쓰임과 동일, 각 요소에 해당 조건에 대한 참, 거짓 여부 판단, 참인 요소의 인덱스 값을 출력한다<br>
새로운 칼럼을 만들 때 많이 사용한다

In [182]:
a = np.array([6,7,8,9,10])
a

array([ 6,  7,  8,  9, 10])

In [183]:
a > 7

array([False, False,  True,  True,  True])

In [184]:
np.where(a>7)    #'a>7'의 조건에 참인 값의 인덱스를 출력

(array([2, 3, 4], dtype=int64),)

In [134]:
a[np.where(a>7)]    #인덱스 번호로 검색

array([ 8,  9, 10])

In [136]:
np.where(a>7, "pass", "fail")

array(['fail', 'fail', 'pass', 'pass', 'pass'], dtype='<U4')

In [139]:
a = np.arange(-15, 15).reshape(5,6) ** 2
a

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]])

In [143]:
np.max(a, axis=1)

array([225,  81,   9,  64, 196])

In [147]:
np.mean(a, axis=0)

array([81., 76., 73., 72., 73., 76.])

In [146]:
a[np.where(a<10)]

array([9, 4, 1, 0, 1, 4, 9])

In [151]:
#0보다 작은 것은 모두 0으로, 크거나 같은 것은 1로 바꾸자
np.where(a<10, 0, 1)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])