### 1007 복습

#### 1

In [3]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

In [4]:
arr = np.array(['TV', '냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서'] * 10)
arr

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고',
       '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지',
       '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지', '컴퓨터',
       '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지', '컴퓨터', '선풍기',
       '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서',
       '믹서', 'TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV',
       '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고',
       '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서', 'TV', '냉장고', '전자레인지',
       '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

In [7]:
encoder = LabelEncoder()
encoder.fit(arr)    #fit : 범위를 잡아주는 정도
labels = encoder.fit_transform(arr)
labels

array([0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3,
       2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5,
       3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2, 0, 1,
       4, 5, 3, 3, 2, 2, 0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

#### 2

In [8]:
from sklearn.datasets import load_iris

In [9]:
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [10]:
iris_data = iris['data']
iris_label = iris['target']

In [12]:
iris_dt = pd.DataFrame(data = iris_data, columns = iris['feature_names'])
iris_dt

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [18]:
iris_dt['label'] = iris['target']
iris_dt

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [19]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [20]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

* label 칼럼의 숫자를 문자로(target_names로) 바꾸기

In [23]:
#내가 생각한 방법
iris_dt['label'] = np.where(iris_dt['label'] == 0, 'setosa',
                            np.where(iris_dt['label'] == 1, 'versicolor', 'virginica'))
iris_dt

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

         label  
0    virginica  
1    virginica  
2    virginica  
3    virginica  
4    virginica  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [ ]:
#다른 방법 - 일대일 대응
label_mapping = {0 : 'setosa', 1 : 'versicolor', 2 : 'virginica'}

iris_dt['label'].map(label_mapping)
iris_dt['label'] = iris_dt['label'].map(label_mapping)

#### 3

In [25]:
d = {'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}
df_dict = pd.DataFrame(d) 
df_dict

col1  col2  col3
0     1     2     3
1    11    22    33

In [33]:
#df를 list로
df_dict.values.tolist()

[[1, 2, 3], [11, 22, 33]]

In [36]:
list(df_dict['col1']) + list(df_dict['col2']) + list(df_dict['col3'])

[1, 11, 2, 22, 3, 33]

In [37]:
df_dict.values.flatten().tolist()

[1, 2, 3, 11, 22, 33]

In [38]:
list(df_dict.values.flatten())

[1, 2, 3, 11, 22, 33]

#### 4

In [45]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [46]:
#7:3 으로 나누자
X_train, X_test, y_trian, y_test = train_test_split(iris_data, iris_label, test_size = 0.3)

### 1011

### (4) 데이터 전처리

#### ② 원-핫 인코딩

In [47]:
from sklearn.preprocessing import OneHotEncoder

In [48]:
items = ['TV', '냉장고', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
encoder = OneHotEncoder()

In [54]:
#2차원 arrary로 변환 -> 데이터가 가로가 아닌 세로로
items = np.array(items).reshape(-1, 1)

In [55]:
encoder.fit(items)    #fit : 행렬의 전체적인 틀을 잡는다

OneHotEncoder()

In [56]:
encoder.transform(items)

<7x5 sparse matrix of type '<class 'numpy.float64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [58]:
one_hot_labels = encoder.transform(items)
one_hot_labels.toarray()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [60]:
items = ['TV', '냉장고', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
pd.get_dummies(items)

TV  냉장고  믹서  선풍기  컴퓨터
0   1    0   0    0    0
1   0    1   0    0    0
2   0    0   0    0    1
3   0    0   0    1    0
4   0    0   0    1    0
5   0    0   1    0    0
6   0    0   1    0    0

### (3) Model Selection 모듈

#### ② 교차 검증 (Cross Validation)

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.datasets import load_iris

In [4]:
# 파일부르기
iris = load_iris()

# data(정보)와 target(매치대상) 저장
iris_data = iris.data
iris_label = iris.target

# 학습과 테스트 구분
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label)
                                     
# 의사결정 트리 
dt_clf = DecisionTreeClassifier()      
    
dt_clf.fit(X_train, y_train)
y_pred = dt_clf.predict(X_test)      # 학습실행, 예측

accuracy_score(y_test, y_pred)

0.9736842105263158

* K 폴드 교차 검증 K-fold CV

In [9]:
from sklearn.model_selection import KFold
import numpy as np

In [10]:
# 파일부르기
iris = load_iris()

# data(정보)와 target(매치대상) 저장
iris_data = iris.data
iris_label = iris.target

# 학습과 테스트 구분
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label)
                                     
# 의사결정 트리 
dt_clf = DecisionTreeClassifier()      

# K 폴드 교차 검증
kfold = KFold(n_splits = 5)    #5개의 폴드 세트로 분리하는 KFold

cv_accuracy = []

#KFold 객체의 split()를 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 반환한다 (중요)
for train_index, test_index in kfold.split(iris_data):
    #kfold.split()로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = iris_data[train_index], iris_data[test_index]
    y_train, y_test = iris_label[train_index], iris_label[test_index]
    
    #학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    
    #반복 시 마다 정확도 측정
    accuracy = accuracy_score(y_test, pred)
    cv_accuracy.append(accuracy)
    
#개별 iteration별 정확도를 합하여 평균 정확도 계산
    print("개별 검증 정확도: ", cv_accuracy)
print('평균 검증 정확도: ', np.mean(cv_accuracy)) 

개별 검증 정확도:  [1.0]
개별 검증 정확도:  [1.0, 1.0]
개별 검증 정확도:  [1.0, 1.0, 0.9]
개별 검증 정확도:  [1.0, 1.0, 0.9, 0.9333333333333333]
개별 검증 정확도:  [1.0, 1.0, 0.9, 0.9333333333333333, 0.8]
평균 검증 정확도:  0.9266666666666665


* stratified K 폴드

In [11]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedKFold

In [12]:
iris = load_iris()

features = x = iris_data = iris.data
labels = y = iris_label = iris.target

In [13]:
df_clf = DecisionTreeClassifier()

In [14]:
s_kfold = StratifiedKFold(n_splits = 3)
cv_accuacy = []

In [20]:
for train_index, test_index in s_kfold.split(features, labels):
    print(train_index)
    print(test_index)
    
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = labels[train_index], labels[test_index]
    
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    
    acc = accuracy_score(y_test, pred)
    cv_accuracy.append(acc)
    print("개별정확도", acc)

print("정확도 모음: ", cv_accuracy)    

[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34
  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  67  68  69
  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87
  88  89  90  91  92  93  94  95  96  97  98  99 116 117 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139
 140 141 142 143 144 145 146 147 148 149]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
개별정확도 0.98
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  34
  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52
  53  54  55  56  57  58  59  60  61  62  63  64  65  66  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104
 105 106 107 108 109 110 111 112 113 114 115 133 134 135 136 137 138 139
 140 141 142 

In [18]:
np.mean(cv_accuracy).round(4)

0.9267

In [ ]:
from sklearn.model_selection import cross_val_score, cross.validate

In [78]:
iris = load_iris()
data = features = X = iris_data = iris.data
label = labels = y = iris_label = iris.target
dt_clf = DecisionTreeClassifier()

In [ ]:
scores = cross_val_score(dt_clf, data, label, scoring = 'accuracy', cv=3)
scores

In [ ]:
np.mean(scores).round(4)

#### ③ GridSearchCV

In [21]:
grid_parameters = {'max_depth' : [1,2,3], 'min_samples_spilt' : [2,3]}

In [23]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, train_test_split

In [33]:
iris = load_iris()

X_train, X_test, y_train, y_test = \
train_test_split(iris.data, iris.target, test_size = 0.2, random_state = 121)

dt_clf = DecisionTreeClassifier()

grid_parameters = {'max_depth' : [1,2,3], 'min_samples_spilt' : [2,3]}

grid_tree = GridSearchCV(dt_clf, param_grid = grid_parameters, cv = 3, refit = True)

In [34]:
#붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_tree.fit(X_train, y_train)

ValueError: Invalid parameter min_samples_spilt for estimator DecisionTreeClassifier(max_depth=1). Check the list of available parameters with `estimator.get_params().keys()`.

In [30]:
grid_tree.cv_results_

AttributeError: 'GridSearchCV' object has no attribute 'cv_results_'

In [32]:
import pandas as pd
pd.DataFrame(grid_tree.cv_results_)

AttributeError: 'GridSearchCV' object has no attribute 'cv_results_'

In [ ]:
pd.DataFrame(grid_tree.cv_results_).iloc[:, 5:]

In [ ]:
grid_tree.best_params_

In [ ]:
grid_tree.best_score_

In [ ]:
pred = grid_tree.predict(X_test)
pred

In [ ]:
accuracy_score(y_test, pred)

#### (4) 데이터 전처리
#### ② 피처 스케일링과 정규화

* 정규화 Normalization<br>
scale을 최소값이 0, 최대값이 1이 되도록 조정하는 것 (0과 1사이의 값이 되도록)<br>
함수를 직접 작성하거나, MinMax Scaler 에 의해 Scaling 한다

In [35]:
iris = iris['data']
iris_df = pd.DataFrame(iris)
iris_df

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [37]:
iris_df.max()

0    7.9
1    4.4
2    6.9
3    2.5
dtype: float64

In [38]:
iris_df.min()

0    4.3
1    2.0
2    1.0
3    0.1
dtype: float64

In [42]:
#정규화 사용자 정의 함수 생성 (최소값은 '0'으로, 최대값은 '1'로)
def min_max(x):
    return (x - x.min()) / (x.max() - x.min())

In [43]:
iris_df.apply(min_max)

0         1         2         3
0    0.222222  0.625000  0.067797  0.041667
1    0.166667  0.416667  0.067797  0.041667
2    0.111111  0.500000  0.050847  0.041667
3    0.083333  0.458333  0.084746  0.041667
4    0.194444  0.666667  0.067797  0.041667
..        ...       ...       ...       ...
145  0.666667  0.416667  0.711864  0.916667
146  0.555556  0.208333  0.677966  0.750000
147  0.611111  0.416667  0.711864  0.791667
148  0.527778  0.583333  0.745763  0.916667
149  0.444444  0.416667  0.694915  0.708333

[150 rows x 4 columns]

In [44]:
#확인
iris_df.apply(min_max).max()

0    1.0
1    1.0
2    1.0
3    1.0
dtype: float64

In [45]:
#사용자 정의 함수를 lambda로
iris_df.apply(lambda x: (x - x.min()) / (x.max() - x.min()))

0         1         2         3
0    0.222222  0.625000  0.067797  0.041667
1    0.166667  0.416667  0.067797  0.041667
2    0.111111  0.500000  0.050847  0.041667
3    0.083333  0.458333  0.084746  0.041667
4    0.194444  0.666667  0.067797  0.041667
..        ...       ...       ...       ...
145  0.666667  0.416667  0.711864  0.916667
146  0.555556  0.208333  0.677966  0.750000
147  0.611111  0.416667  0.711864  0.791667
148  0.527778  0.583333  0.745763  0.916667
149  0.444444  0.416667  0.694915  0.708333

[150 rows x 4 columns]

In [46]:
iris_df.apply(lambda x: (x - x.min()) / (x.max() - x.min())).min()

0    0.0
1    0.0
2    0.0
3    0.0
dtype: float64

* MinMaxScaler 사용하기

In [47]:
from sklearn.preprocessing import MinMaxScaler

In [48]:
#MinMaxScaler 객체 생성
scaler = MinMaxScaler()

#MinMaxScaler로 데이터 세트 변환 -> fit() 과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_scaled

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [50]:
#fit_transform() 으로 한번에 처리할 수도 있다
iris_scaled = scaler.fit_transform(iris_df)
iris_scaled

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [ ]:
X_train, X_test = train_test_split(iris_data)

In [ ]:
X_train

scaler.fit()
scaler.transform()

In [ ]:
X_test

scaler.fit()
scaler.transform()

X_train과 X_test 따로 정규화시키면 각각 다른 값이 나올 수 있다 (fit을 각각 실행했기 때문에)<br>
X_train에서 먼저 fit을 실행했다면 X_test에서는 fit은 실행하지 않고 transform 만 실행하면 된다<br>
아니면 train과 test로 분리하기 전에, 먼저 전체 데이터의 스케일링 변환을 적용하고<br>
그 후에 train과 test로 분리하는 것이 좋다

* 표준화 Standardization<br>
표준정규분포; 어떤 단위이든 상관없이 평균을 0, 표준편차(분산)를 1로 조정한다<br>
x - mu / sigma

In [54]:
#표준화 사용자 정의 함수
def standardize(x):
    return (x - x.mean()) / x.std()

In [55]:
iris_df
iris_df.apply(standardize)    #각각의 칼럼별로 표준화 된다

0         1         2         3
0   -0.897674  1.015602 -1.335752 -1.311052
1   -1.139200 -0.131539 -1.335752 -1.311052
2   -1.380727  0.327318 -1.392399 -1.311052
3   -1.501490  0.097889 -1.279104 -1.311052
4   -1.018437  1.245030 -1.335752 -1.311052
..        ...       ...       ...       ...
145  1.034539 -0.131539  0.816859  1.443994
146  0.551486 -1.278680  0.703564  0.919223
147  0.793012 -0.131539  0.816859  1.050416
148  0.430722  0.786174  0.930154  1.443994
149  0.068433 -0.131539  0.760211  0.788031

[150 rows x 4 columns]

* StandardScaler 사용하기

In [56]:
from sklearn.preprocessing import StandardScaler

In [ ]:
#StandardScaler 객체 생성
scaler = StandardScaler()

#StandardScaler로 데이터 세트 변환 -> fit() 과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_scaled