In [1]:
import pydataset

In [17]:
import pandas as pd
import numpy as np

In [3]:
mpg = pydataset.data("mpg")
mpg[:5]

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [5]:
#연료 종류(fl)를 레이블 값으로 설정해 이를 예측할 수 있는지 머신러닝을 구현해보자
from collections import Counter
Counter(mpg.fl)

Counter({'p': 52, 'r': 168, 'e': 8, 'd': 5, 'c': 1})

In [6]:
#연료 종류 중 'e','d','c' 의 개수는 적으므로 삭제
mpg.fl.value_counts()

r    168
p     52
e      8
d      5
c      1
Name: fl, dtype: int64

In [14]:
#방법1
mpg.loc[(mpg.fl == 'p') | (mpg.fl == 'r')]

#cond1 = mpg.fl == 'p'
#cond2 = mpg.fl == 'r'
#mpg.loc[cond1 | cond2]

manufacturer   model  displ  year  cyl       trans drv  cty  hwy fl  \
1           audi      a4    1.8  1999    4    auto(l5)   f   18   29  p   
2           audi      a4    1.8  1999    4  manual(m5)   f   21   29  p   
3           audi      a4    2.0  2008    4  manual(m6)   f   20   31  p   
4           audi      a4    2.0  2008    4    auto(av)   f   21   30  p   
5           audi      a4    2.8  1999    6    auto(l5)   f   16   26  p   
..           ...     ...    ...   ...  ...         ...  ..  ...  ... ..   
230   volkswagen  passat    2.0  2008    4    auto(s6)   f   19   28  p   
231   volkswagen  passat    2.0  2008    4  manual(m6)   f   21   29  p   
232   volkswagen  passat    2.8  1999    6    auto(l5)   f   16   26  p   
233   volkswagen  passat    2.8  1999    6  manual(m5)   f   18   26  p   
234   volkswagen  passat    3.6  2008    6    auto(s6)   f   17   26  p   

       class  
1    compact  
2    compact  
3    compact  
4    compact  
5    compact  
..       ...  
230  midsize  
231  midsize  
232  midsize  
233  midsize  
234  midsize  

[220 rows x 11 columns]

In [20]:
#방법2
mpg.query("fl == 'p' | fl == 'r'")

manufacturer   model  displ  year  cyl       trans drv  cty  hwy fl  \
1           audi      a4    1.8  1999    4    auto(l5)   f   18   29  p   
2           audi      a4    1.8  1999    4  manual(m5)   f   21   29  p   
3           audi      a4    2.0  2008    4  manual(m6)   f   20   31  p   
4           audi      a4    2.0  2008    4    auto(av)   f   21   30  p   
5           audi      a4    2.8  1999    6    auto(l5)   f   16   26  p   
..           ...     ...    ...   ...  ...         ...  ..  ...  ... ..   
230   volkswagen  passat    2.0  2008    4    auto(s6)   f   19   28  p   
231   volkswagen  passat    2.0  2008    4  manual(m6)   f   21   29  p   
232   volkswagen  passat    2.8  1999    6    auto(l5)   f   16   26  p   
233   volkswagen  passat    2.8  1999    6  manual(m5)   f   18   26  p   
234   volkswagen  passat    3.6  2008    6    auto(s6)   f   17   26  p   

       class  
1    compact  
2    compact  
3    compact  
4    compact  
5    compact  
..       ...  
230  midsize  
231  midsize  
232  midsize  
233  midsize  
234  midsize  

[220 rows x 11 columns]

In [19]:
#방법3
mpg['fl'].replace(['e','d','c'], np.nan, inplace = True)
mpg['fl'].dropna()

1      p
2      p
3      p
4      p
5      p
      ..
230    p
231    p
232    p
233    p
234    p
Name: fl, Length: 220, dtype: object

In [ ]:
#방법4
a = mpg[mpg['f1'] == 'p']
b = mpg[mpg['f1'] == 'r']
pd.concat([a,b], axis=0)

In [34]:
mpg

manufacturer   model  displ  year  cyl       trans drv  cty  hwy fl  \
1           audi      a4    1.8  1999    4    auto(l5)   f   18   29  p   
2           audi      a4    1.8  1999    4  manual(m5)   f   21   29  p   
3           audi      a4    2.0  2008    4  manual(m6)   f   20   31  p   
4           audi      a4    2.0  2008    4    auto(av)   f   21   30  p   
5           audi      a4    2.8  1999    6    auto(l5)   f   16   26  p   
..           ...     ...    ...   ...  ...         ...  ..  ...  ... ..   
230   volkswagen  passat    2.0  2008    4    auto(s6)   f   19   28  p   
231   volkswagen  passat    2.0  2008    4  manual(m6)   f   21   29  p   
232   volkswagen  passat    2.8  1999    6    auto(l5)   f   16   26  p   
233   volkswagen  passat    2.8  1999    6  manual(m5)   f   18   26  p   
234   volkswagen  passat    3.6  2008    6    auto(s6)   f   17   26  p   

       class  
1    compact  
2    compact  
3    compact  
4    compact  
5    compact  
..       ...  
230  midsize  
231  midsize  
232  midsize  
233  midsize  
234  midsize  

[234 rows x 11 columns]

In [24]:
features = mpg.drop('fl', axis = 1)
labels = mpg[['fl']]

In [30]:
#레이블 인코딩
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [25]:
features.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 234 entries, 1 to 234
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   manufacturer  234 non-null    object 
 1   model         234 non-null    object 
 2   displ         234 non-null    float64
 3   year          234 non-null    int64  
 4   cyl           234 non-null    int64  
 5   trans         234 non-null    object 
 6   drv           234 non-null    object 
 7   cty           234 non-null    int64  
 8   hwy           234 non-null    int64  
 9   class         234 non-null    object 
dtypes: float64(1), int64(4), object(5)
memory usage: 28.2+ KB


In [29]:
mpg['manufacturer']

1            audi
2            audi
3            audi
4            audi
5            audi
          ...    
230    volkswagen
231    volkswagen
232    volkswagen
233    volkswagen
234    volkswagen
Name: manufacturer, Length: 234, dtype: object

In [36]:
columns = features.columns

for column in columns:
    encoder.fit(features[column])
    encoded = encoder.transform(features[column])
    features[column] = encoded
    
features

manufacturer  model  displ  year  cyl  trans  drv  cty  hwy  class
1               0      1      1     0    0      3    1    8   16      1
2               0      1      1     0    0      8    1   11   16      1
3               0      1      3     1    0      9    1   10   18      1
4               0      1      3     1    0      0    1   11   17      1
5               0      1      8     0    2      3    1    6   13      1
..            ...    ...    ...   ...  ...    ...  ...  ...  ...    ...
230            14     31      3     1    0      7    1    9   15      2
231            14     31      3     1    0      9    1   11   16      2
232            14     31      8     0    2      3    1    6   13      2
233            14     31      8     0    2      8    1    8   13      2
234            14     31     14     1    2      7    1    7   13      2

[234 rows x 10 columns]

In [41]:
labels = encoder.fit_transform(labels)
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 2, 1, 1, 0, 0, 1, 1, 1,
       1, 2, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [42]:
#cross_val_score(), DecisionTree 사용
#정제한 데이터를 5개의 구간으로 나누고, 평가 지표는 '정확도' 사용
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier()

scores = cross_val_score(dt_clf, features, labels, scoring = 'accuracy', cv = 5)
print(scores)
np.mean(scores).round(4)

[0.46808511 0.87234043 0.55319149 0.53191489 0.43478261]


0.5721

### (9) 분류 실습 - 캐글 신용카드 사기 검출
https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud

#### * 언더 샘플링과 오버 샘플링의 이해
imbalanced-learn 설치<br>
아나콘다 프롬프트 실행
conda install -c conda-forge imbalanced-learn 입력

#### * 데이터 일차 가공 및 모델 학습/예측/평가

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [50]:
card = pd.read_csv("creditcard.csv")
card

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [51]:
card.shape

(284807, 31)

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
#1. Time 칼럼 삭제
card.drop(['Time'], axis = 1, inplace = True)

In [55]:
#2. 데이터세트 분리
features = card.iloc[:, :-1]
labels = card.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size = 0.3, random_state = 0)

In [56]:
y_train.value_counts() / len(y_train)

0    0.99831
1    0.00169
Name: Class, dtype: float64

In [59]:
#3. 모델 생성 및 fit, predict, evaluate
from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression(max_iter = 1000)
lr_clf.fit(X_train, y_train)
preds = lr_clf.predict(X_test)
pred_proba = lr_clf.predict_proba(X_test)[:, 1]

In [60]:
from sklearn.metrics import roc_auc_score, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

def get_clf_eval(y_test, pred=None, pred_proba=None):
    confusion = confusion_matrix( y_test, pred)
    accuracy = accuracy_score(y_test , pred)
    precision = precision_score(y_test , pred)
    recall = recall_score(y_test , pred)
    f1 = f1_score(y_test,pred)
    # ROC-AUC 추가 
    roc_auc = roc_auc_score(y_test, pred_proba)
    print('오차 행렬')
    print(confusion)
    # ROC-AUC print 추가
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f},\
    F1: {3:.4f}, AUC:{4:.4f}'.format(accuracy, precision, recall, f1, roc_auc))

In [61]:
get_clf_eval(y_test, preds, pred_proba)

오차 행렬
[[85274    14]
 [   57    98]]
정확도: 0.9992, 정밀도: 0.8750, 재현율: 0.6323,    F1: 0.7341, AUC:0.9799


오차행렬<br>
TN      FP<br>
FN      TP

In [62]:
labels.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [63]:
#3-1. LightGBM
from lightgbm import LGBMClassifier

lgbm_clf = LGBMClassifier(n_estimators = 1000, num_leaves = 64, n_jobs = -1, boost_from_average = False)

lgbm_clf.fit(X_train, y_train)
preds = lgbm_clf.predict(X_test)
pred_proba = lgbm_clf.predict_proba(X_test)[:, 1]

In [64]:
get_clf_eval(y_test, preds, pred_proba)

오차 행렬
[[85280     8]
 [   28   127]]
정확도: 0.9996, 정밀도: 0.9407, 재현율: 0.8194,    F1: 0.8759, AUC:0.9846


#### * 데이터 분포도 변환 후 모델 학습/예측/평가

In [66]:
card['Amount']
card['Amount'].describe()

count    284807.000000
mean         88.349619
std         250.120109
min           0.000000
25%           5.600000
50%          22.000000
75%          77.165000
max       25691.160000
Name: Amount, dtype: float64

In [68]:
#표준화
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

s = scaler.fit_transform(card['Amount'].values.reshape(-1, 1))

In [69]:
card['Amount_temp'] = s

In [70]:
card

V1         V2        V3        V4        V5        V6  \
0       -1.359807  -0.072781  2.536347  1.378155 -0.338321  0.462388   
1        1.191857   0.266151  0.166480  0.448154  0.060018 -0.082361   
2       -1.358354  -1.340163  1.773209  0.379780 -0.503198  1.800499   
3       -0.966272  -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4       -1.158233   0.877737  1.548718  0.403034 -0.407193  0.095921   
...           ...        ...       ...       ...       ...       ...   
284802 -11.881118  10.071785 -9.834783 -2.066656 -5.364473 -2.606837   
284803  -0.732789  -0.055080  2.035030 -0.738589  0.868229  1.058415   
284804   1.919565  -0.301254 -3.249640 -0.557828  2.630515  3.031260   
284805  -0.240440   0.530483  0.702510  0.689799 -0.377961  0.623708   
284806  -0.533413  -0.189733  0.703337 -0.506271 -0.012546 -0.649617   

              V7        V8        V9       V10  ...       V22       V23  \
0       0.239599  0.098698  0.363787  0.090794  ...  0.277838 -0.110474   
1      -0.078803  0.085102 -0.255425 -0.166974  ... -0.638672  0.101288   
2       0.791461  0.247676 -1.514654  0.207643  ...  0.771679  0.909412   
3       0.237609  0.377436 -1.387024 -0.054952  ...  0.005274 -0.190321   
4       0.592941 -0.270533  0.817739  0.753074  ...  0.798278 -0.137458   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -4.918215  7.305334  1.914428  4.356170  ...  0.111864  1.014480   
284803  0.024330  0.294869  0.584800 -0.975926  ...  0.924384  0.012463   
284804 -0.296827  0.708417  0.432454 -0.484782  ...  0.578229 -0.037501   
284805 -0.686180  0.679145  0.392087 -0.399126  ...  0.800049 -0.163298   
284806  1.577006 -0.414650  0.486180 -0.915427  ...  0.643078  0.376777   

             V24       V25       V26       V27       V28  Amount  Class  \
0       0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62      0   
1      -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69      0   
2      -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0   
3      -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50      0   
4       0.141267 -0.206010  0.502292  0.219422  0.215153   69.99      0   
...          ...       ...       ...       ...       ...     ...    ...   
284802 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77      0   
284803 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79      0   
284804  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88      0   
284805  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00      0   
284806  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00      0   

        Amount_temp  
0          0.244964  
1         -0.342475  
2          1.160686  
3          0.140534  
4         -0.073403  
...             ...  
284802    -0.350151  
284803    -0.254117  
284804    -0.081839  
284805    -0.313249  
284806     0.514355  

[284807 rows x 31 columns]

In [72]:
card.drop('Amount_temp', axis =1, inplace = True)
card[:5]

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0  0.098698  0.363787  0.090794  ... -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425 -0.166974  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  0.207643  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024 -0.054952  ... -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  0.753074  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 30 columns]

In [75]:
from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression(max_iter = 1000)
lr_clf.fit(X_train, y_train)
preds = lr_clf.predict(X_test)
pred_proba = lr_clf.predict_proba(X_test)[:, 1]

In [73]:
from lightgbm import LGBMClassifier

lgbm_clf = LGBMClassifier(n_estimators = 1000, num_leaves = 64, n_jobs = -1, boost_from_average = False)

lgbm_clf.fit(X_train, y_train)
preds = lgbm_clf.predict(X_test)
pred_proba = lgbm_clf.predict_proba(X_test)[:, 1]

In [74]:
get_clf_eval(y_test, preds, pred_proba)

오차 행렬
[[85280     8]
 [   28   127]]
정확도: 0.9996, 정밀도: 0.9407, 재현율: 0.8194,    F1: 0.8759, AUC:0.9846


#### * 데이터 정제(로그 변환) 후 작용

In [ ]:
card = pd.read_csv("creditcard.csv")
card

#1. Time 칼럼 삭제
card.drop(['Time'], axis = 1, inplace = True)

In [78]:
#로그 변환하기
np.log1p(card['Amount'])

0         5.014760
1         1.305626
2         5.939276
3         4.824306
4         4.262539
            ...   
284802    0.570980
284803    3.249987
284804    4.232366
284805    2.397895
284806    5.384495
Name: Amount, Length: 284807, dtype: float64

In [77]:
card['Amount']

0         149.62
1           2.69
2         378.66
3         123.50
4          69.99
           ...  
284802      0.77
284803     24.79
284804     67.88
284805     10.00
284806    217.00
Name: Amount, Length: 284807, dtype: float64

In [79]:
#log를 사용하는 이유 -> 숫자가 너무 커서, 큰 숫자를 줄여준다

card['Amount'] = np.log1p(card['Amount'])
card['Amount']

0         5.014760
1         1.305626
2         5.939276
3         4.824306
4         4.262539
            ...   
284802    0.570980
284803    3.249987
284804    4.232366
284805    2.397895
284806    5.384495
Name: Amount, Length: 284807, dtype: float64

In [83]:
lr_clf = LogisticRegression(max_iter = 1000)
lr_clf.fit(X_train, y_train)
preds = lr_clf.predict(X_test)
pred_proba = lr_clf.predict_proba(X_test)[:, 1]

In [84]:
get_clf_eval(y_test, preds, pred_proba)

오차 행렬
[[85274    14]
 [   57    98]]
정확도: 0.9992, 정밀도: 0.8750, 재현율: 0.6323,    F1: 0.7341, AUC:0.9799


In [85]:
lgbm_clf = LGBMClassifier(n_estimators = 1000, num_leaves = 64, n_jobs = -1, boost_from_average = False)

lgbm_clf.fit(X_train, y_train)
preds = lgbm_clf.predict(X_test)
pred_proba = lgbm_clf.predict_proba(X_test)[:, 1]

In [86]:
get_clf_eval(y_test, preds, pred_proba)

오차 행렬
[[85280     8]
 [   28   127]]
정확도: 0.9996, 정밀도: 0.9407, 재현율: 0.8194,    F1: 0.8759, AUC:0.9846


#### * 이상치 데이터 제거 후 모델 학습/예측/평가

In [ ]:
#1. 이상치 찾기 (IQR 적용)
#IQR = 3/4 - 1/4
#3/4 + 1.5IQR, #1/4 - 1.5IQR

In [133]:
card.query("Class == 1")
#fraud = card[card['Class'] == 1]
#fraud

V1        V2        V3        V4        V5        V6        V7  \
541    -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545 -2.537387   
623    -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823  0.325574   
4920   -2.303350  1.759247 -0.359745  2.330243 -0.821628 -0.075788  0.562320   
6108   -4.397974  1.358367 -2.592844  2.679787 -1.128131 -1.706536 -3.496197   
6329    1.234235  3.019740 -4.304597  4.732795  3.624201 -1.357746  1.713445   
...          ...       ...       ...       ...       ...       ...       ...   
279863 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494 -0.882850   
280143  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536 -1.413170   
280149 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346 -2.234739   
281144 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548 -2.208002   
281674  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695  0.223050   

              V8        V9       V10  ...       V21       V22       V23  \
541     1.391657 -2.770089 -2.772272  ...  0.517232 -0.035049 -0.465211   
623    -0.067794 -0.270953 -0.838587  ...  0.661696  0.435477  1.375966   
4920   -0.399147 -0.238253 -1.525412  ... -0.294166 -0.932391  0.172726   
6108   -0.248778 -0.247768 -4.801637  ...  0.573574  0.176968 -0.436207   
6329   -0.496358 -1.282858 -2.447469  ... -0.379068 -0.704181 -0.656805   
...          ...       ...       ...  ...       ...       ...       ...   
279863  0.697211 -2.064945 -5.587794  ...  0.778584 -0.319189  0.639419   
280143  0.248525 -1.127396 -3.232153  ...  0.370612  0.028234 -0.145640   
280149  1.210158 -0.652250 -3.463891  ...  0.751826  0.834108  0.190944   
281144  1.058733 -1.632333 -5.245984  ...  0.583276 -0.269209 -0.456108   
281674 -0.068384  0.577829 -0.888722  ... -0.164350 -0.295135 -0.072173   

             V24       V25       V26       V27       V28    Amount  Class  
541     0.320198  0.044519  0.177840  0.261145 -0.143276  0.000000      1  
623    -0.293803  0.279798 -0.145362 -0.252773  0.035764  6.272877      1  
4920   -0.087330 -0.156114 -0.542628  0.039566 -0.153029  5.484506      1  
6108   -0.053502  0.252405 -0.657488 -0.827136  0.849573  4.094345      1  
6329   -1.632653  1.488901  0.566797 -0.010016  0.146793  0.693147      1  
...          ...       ...       ...       ...       ...       ...    ...  
279863 -0.294885  0.537503  0.788395  0.292680  0.147968  5.968708      1  
280143 -0.081049  0.521875  0.739467  0.389152  0.186637  0.565314      1  
280149  0.032070 -0.739695  0.471111  0.385107  0.194361  4.368054      1  
281144 -0.183659 -0.328168  0.606116  0.884876 -0.253700  5.505332      1  
281674 -0.450261  0.313267 -0.289617  0.002988 -0.015309  3.773450      1  

[488 rows x 30 columns]

In [99]:
#V14 칼럼에서 이상치 데이터 찾기
fraud['V14']

541      -4.289254
623      -1.692029
4920     -1.470102
6108     -6.771097
6329     -6.079337
            ...   
279863   -6.665177
280143   -5.210141
280149   -4.057162
281144   -6.416628
281674   -1.948883
Name: V14, Length: 492, dtype: float64

In [101]:
pct25 = fraud['V14'].quantile(0.25)
pct75 = fraud['V14'].quantile(0.75)
IQR = pct75 - pct25
IQR.round(6)

5.409902

In [109]:
IQR = IQR.round(6)

higtest = pct75 + 1.5*IQR
lowest = pct25 - 1.5*IQR

fraud['V14'][(fraud['V14'] < lowest) | (fraud['V14'] > higtest)]

8296   -19.214325
8615   -18.822087
9035   -18.493773
9252   -18.049998
Name: V14, dtype: float64

In [117]:
outlier = fraud['V14'][(fraud['V14'] < lowest) | (fraud['V14'] > higtest)]
outlier.index

Int64Index([8296, 8615, 9035, 9252], dtype='int64')

In [120]:
#이상치 제거
card[:5]
card.shape

card.drop(outlier.index, axis = 0, inplace = True)
#card.drop(labels = [8296, 8615, 9035, 9252], axis = 0)

In [121]:
features = card.iloc[:, :-1]
labels = card.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size = 0.3, random_state = 0)

In [122]:
lr_clf = LogisticRegression(max_iter = 1000)
lr_clf.fit(X_train, y_train)
preds = lr_clf.predict(X_test)
pred_proba = lr_clf.predict_proba(X_test)[:, 1]

In [123]:
get_clf_eval(y_test, preds, pred_proba)

오차 행렬
[[85283    16]
 [   52    90]]
정확도: 0.9992, 정밀도: 0.8491, 재현율: 0.6338,    F1: 0.7258, AUC:0.9722


In [124]:
lgbm_clf = LGBMClassifier(n_estimators = 1000, num_leaves = 64, n_jobs = -1, boost_from_average = False)

lgbm_clf.fit(X_train, y_train)
preds = lgbm_clf.predict(X_test)
pred_proba = lgbm_clf.predict_proba(X_test)[:, 1]

In [125]:
get_clf_eval(y_test, preds, pred_proba)

오차 행렬
[[85295     4]
 [   29   113]]
정확도: 0.9996, 정밀도: 0.9658, 재현율: 0.7958,    F1: 0.8726, AUC:0.9754


#### * SMOTE 오버 샘플링 적용 후 모델 학습/예측/평가

In [135]:
pip install imbalanced-learn

In [136]:
from imblearn.over_sampling import SMOTE

ImportError: cannot import name '_ClassNamePrefixFeaturesOutMixin' from 'sklearn.base' (C:\Users\admin\anaconda3\lib\site-packages\sklearn\base.py)

In [ ]:
#1. 데이터 셋 분리
features = card.iloc[:, :-1]
labels = card.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size = 0.3, random_state = 0)

In [ ]:
X_train.shape

In [ ]:
y_train.shape

In [ ]:
X_test.shape

In [ ]:
y_test.shape

In [ ]:
y_train.shape.value_counts()

In [ ]:
#2. SMOTE 적용
smote = SMOTE(random_state = 0)
X_train, y_train = smote.fit_resample(X_train, y_train)

In [ ]:
y_train.shape.value_counts()

In [ ]:
#3. 모델 생성, fit/predict/evaluate
lr_clf = LogisticRegression(max_iter = 1000)
lr_clf.fit(X_train, y_train)
preds = lr_clf.predict(X_test)
pred_proba = lr_clf.predict_proba(X_test)[:, 1]
print(get_clf_eval(y_test, preds, pred_proba))
print()

lgbm_clf = LGBMClassifier(n_estimators = 1000, num_leaves = 64, n_jobs = -1, boost_from_average = False)
lgbm_clf.fit(X_train, y_train)
preds = lgbm_clf.predict(X_test)
pred_proba = lgbm_clf.predict_proba(X_test)[:, 1]
print(get_clf_eval(y_test, preds, pred_proba))