### 1025

#### 1

In [2]:
import pandas as pd
import numpy as np

from nltk import word_tokenize
from nltk.stem import PorterStemmer

In [3]:
text = "Now I am going to have dinner with my wife. Thanks for having me here." 

words = word_tokenize(text)

stemmer = PorterStemmer()

stem_list = []

for word in words:
    stemmed = stemmer.stem(word)
    stem_list.append(stemmed)
    
stem_list

['now',
 'i',
 'am',
 'go',
 'to',
 'have',
 'dinner',
 'with',
 'my',
 'wife',
 '.',
 'thank',
 'for',
 'have',
 'me',
 'here',
 '.']

In [4]:
text = "Now I am going to have dinner with my wife. Thanks for having me here." 

words = word_tokenize(text)

stemmer = PorterStemmer()

[stemmer.stem(word) for word in words]

['now',
 'i',
 'am',
 'go',
 'to',
 'have',
 'dinner',
 'with',
 'my',
 'wife',
 '.',
 'thank',
 'for',
 'have',
 'me',
 'here',
 '.']

#### 2

In [5]:
sentence = "Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop. " 

words = word_tokenize(sentence)
len(words)

25

#### 3

In [6]:
from scipy import sparse

In [7]:
data= np.array([3, 5, 2])
row = np.array([3, 2, 2])
col = np.array([2, 3, 4])

sparse_coo = sparse.coo_matrix((data, (row, col)), shape=(5,6)).toarray()
sparse_coo

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 2, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [8]:
data= np.array([2, 5, 3])
row_index = np.array([0, 0, 0, 2, 3, 3])
col = np.array([4, 3, 2])

sparse_csr = sparse.csr_matrix((data, col, row_index), shape=(5,6)).toarray()
sparse_csr

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 2, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [9]:
data= np.array([4, 5, 2, 3])
row_index = np.array([0, 0, 0, 3, 4, 4])
col = np.array([2, 3, 4, 2])

sparse_csr = sparse.csr_matrix((data, col, row_index), shape=(5,6)).toarray()
sparse_csr

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 4, 5, 2, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [15]:
data= np.array([1, 2, 4, 5, 2, 3])
#row = np.array([0, 0, 2, 2, 2, 4])
row_index = np.array([0, 2, 2, 5, 5, 6])
col = np.array([0, 1, 2, 3, 4, 2])

sparse_csr = sparse.csr_matrix((data, col, row_index), shape=(5,6)).toarray()
sparse_csr

array([[1, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 4, 5, 2, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0]])

In [ ]:
문서와 문서 간의 유사도 비교는 일반적으로 '코사인 유사도' 를 사용한다

문서 집합에 숨어있는 주제를 찾아내는 모델링 방법은 '토픽 모델링' 이다

텍스트 분석 패키지 중 주로 소셜 미디어 텍스트에 대한 감성분석을 제공하고,
뛰어난 감성 분선결과 및 빠른 수행시간으로 대용량 텍스트 데이터에 잘 사용되는 패키지는 'VADER' 이다

자연어를 기계가 이해할 수 있는 숫자의 나열인 벡터로 바꾸어 주는 것을 '피처 벡터화' 라고 한다

두 문장에서 같은 단어가 자주 나타나면 코사인 유사도가 '높은' 것이다

KMeans 객체의 clusters_centers 속성은 0에서 1의 값을 가지며, 1에 가까울수록 중심에 가까운 값이다.

### 1026

## 9. 추천 시스템
추천 시스템의 대표적인 방식으로는 '콘텐츠 기반 필터링' 과 '협업 필터링' 이 있다

#### 콘텐츠 기반 필터링
아이템(상품, 영화, 서비스 등)을 구성하는 여러 가지 콘텐츠 중 사용자가 좋아하는 콘텐츠를 필터링하여 이에 맞는 아이템을 추천하는 방식이다<br>
예: 사용자가 좋아하는 영화를 분석한 뒤, 그 영화의 콘텐츠(장르, 감독, 영화배우 등)와 유사한 다른 영화를 추천하는 것<br>
콘텐츠 요소들을 결합하여 하나의 콘텐츠 특징으로 피처 벡터화한 후에 이 피처 벡터와 가장 유사한 피처 벡터를 가진 다른 영화를 추천하는 것<br>

#### 협업 필터링 - 최근접 이웃 협업 필터링, 잠재 요인 협업 필터링
* 최근접 이웃 협업 필터링<br>
사용자 기반과 아이템 기반 방식으로 나뉜다<br>
아이템 기반 최근접 이웃 방식은 특정 아이템과 가장 유사한 다른 아이템을 추천하는 것이다<br>
이때 유사도의 기준이 되는 것은 사용자들의 아이템에 대한 평가를 벡터화한 값이다 (코사인 유사도를 이용한다)<br>

* 잠재 요인 협업 필터링<br>
사용자-아이템 평점 행렬 데이터에 숨어있는 잠재 요인을 추출하여 사용자가 아직 평점을 매기지 않은 아이템에 대한 평점을 예측하고 이를 추천에 반영하는 방식이다<br>
다차원의 사용자-아이템 평점 행렬을 저차원의 사용자-잠재요인, 아이템-잠재요인 행렬로 분해하는 '행렬 분해' 기법을 사용한다

### (5) 콘텐츠 기반 필터링 실습 - TMDB 5000 영화 데이터 세트
#### * 장르 속성을 이용한 영화 콘텐츠 기반 필터링
장르 칼럼 값의 유사도를 비교한 뒤 그중 높은 평점을 가지는 영화를 추천한다
(콘텐츠 기반 필터링 방식 : 사용자가 특정한 아이템을 매우 선호하는 경우, 그 아이템과 비슷한 콘텐츠를 가진 다른 아이템을 추천하는 것)

#### ① 데이터 로딩 및 가공

In [1]:
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')

In [21]:
movies = pd.read_csv('tmdb_5000_movies.csv')
movies[:5]

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [22]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  production_countries  4803 non-null   object 
 11  release_date          4802 non-null   object 
 12  revenue               4803 non-null   int64  
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object 
 15  status               

In [23]:
movies.shape

(4803, 20)

In [24]:
movies_df = movies.iloc[:, [3, 17, 1, 18, 19, 8, 4, 7]]
movies_df[:5]

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                              genres  vote_average  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1   

   vote_count  popularity                                           keywords  \
0       11800  150.437577  [{"id": 1463, "name": "culture clash"}, {"id":...   
1        4500  139.082615  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2        4466  107.376788  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3        9106  112.312950  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4        2124   43.926995  [{"id": 818, "name": "based on novel"}, {"id":...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [25]:
#pandas 의 하나의 셀 안에는 리스트나 딕셔너리가 들어갈 수 없다(단순한 문자열 형태로 로딩됨)
print(movies['genres'][0])
print(movies['genres'][0][0])
print(movies['genres'][0][1])

[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]
[
{


* genres 칼럼의 문자열을 분해해서 리스트 객체로 추출<br>
파이썬 ast 모듈의 literal_eval() 함수 -> 문자열을 list [dict1, dict2] 객체로 만들 수 있다

In [26]:
from ast import literal_eval

In [27]:
print(literal_eval("{'id' : 28, 'name' : 'Action'}"))
print(type(literal_eval("{'id' : 28, 'name' : 'Action'}")))

{'id': 28, 'name': 'Action'}
<class 'dict'>


In [18]:
movies['genres']
#literal_eval("movies['geners'][0][0]")

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...                        
4798    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801                                                   []
4802                  [{"id": 99, "name": "Documentary"}]
Name: genres, Length: 4803, dtype: object

In [28]:
movies_df['genres'] = movies_df['genres'].apply(literal_eval)
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)
movies_df[:5]

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                              genres  vote_average  \
0  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...           7.2   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...           6.9   
2  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...           6.3   
3  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...           7.6   
4  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...           6.1   

   vote_count  popularity                                           keywords  \
0       11800  150.437577  [{'id': 1463, 'name': 'culture clash'}, {'id':...   
1        4500  139.082615  [{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...   
2        4466  107.376788  [{'id': 470, 'name': 'spy'}, {'id': 818, 'name...   
3        9106  112.312950  [{'id': 849, 'name': 'dc comics'}, {'id': 853,...   
4        2124   43.926995  [{'id': 818, 'name': 'based on novel'}, {'id':...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [29]:
movies_df['genres'][0]

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [32]:
#장르명만 추출
for i in movies_df['genres'][0]:
    print(i['name'])

Action
Adventure
Fantasy
Science Fiction


In [33]:
[i['name'] for i in movies_df['genres'][0]]

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [34]:
movies_df['genres'] = movies_df['genres'].apply(lambda x: [y['name'] for y in x])
movies_df['keywords'] = movies_df['keywords'].apply(lambda x: [y['name'] for y in x])
movies_df[:5]

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                          genres  vote_average  vote_count  \
0  [Action, Adventure, Fantasy, Science Fiction]           7.2       11800   
1                   [Adventure, Fantasy, Action]           6.9        4500   
2                     [Action, Adventure, Crime]           6.3        4466   
3               [Action, Crime, Drama, Thriller]           7.6        9106   
4           [Action, Adventure, Science Fiction]           6.1        2124   

   popularity                                           keywords  \
0  150.437577  [culture clash, future, space war, space colon...   
1  139.082615  [ocean, drug abuse, exotic island, east india ...   
2  107.376788  [spy, based on novel, secret agent, sequel, mi...   
3  112.312950  [dc comics, crime fighter, terrorist, secret i...   
4   43.926995  [based on novel, mars, medallion, space travel...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

#### ② 장르 콘텐츠 유사도 측정
genres 칼럼을 문자열로 변경한 뒤 이를 CountVectorizer로 피처 벡터화한 행렬 데이터 값을 코사인 유사도로 비교한다

1) CountVectorizer 를 적용하기 위해 문자열로 변환

In [35]:
from sklearn.feature_extraction.text import CountVectorizer

In [36]:
#CountVectorizer 를 적용하기 위해 문자열로 변환
movies_df['genres_literal'] = movies_df['genres'].apply(lambda x: " ".join(x))

cnt_vect = CountVectorizer(min_df=0, ngram_range=(1,2))

genre_mat = cnt_vect.fit_transform(movies_df['genres_literal'])
genre_mat.shape

(4803, 276)

2) 코사인 유사도 측정

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

In [38]:
cosine_similarity(genre_mat, genre_mat)

array([[1.        , 0.59628479, 0.4472136 , ..., 0.        , 0.        ,
        0.        ],
       [0.59628479, 1.        , 0.4       , ..., 0.        , 0.        ,
        0.        ],
       [0.4472136 , 0.4       , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [39]:
genre_sim = cosine_similarity(genre_mat, genre_mat)
np.argsort(genre_sim)    #np.argsort() : index 번호를 sorting

array([[2401, 3037, 3038, ...,  813, 3494,    0],
       [2401, 3067, 3069, ...,  129,    1,  262],
       [2401, 2999, 3000, ..., 1542, 1740,    2],
       ...,
       [   0, 2230, 2229, ..., 1895, 3809, 4800],
       [   0, 3205, 3204, ..., 1596, 1594, 4802],
       [   0, 3141, 3140, ..., 4521, 4710, 4802]], dtype=int64)

In [40]:
#유사도가 높은 것 부터 정렬
np.argsort(genre_sim)[:, ::-1]

array([[   0, 3494,  813, ..., 3038, 3037, 2401],
       [ 262,    1,  129, ..., 3069, 3067, 2401],
       [   2, 1740, 1542, ..., 3000, 2999, 2401],
       ...,
       [4800, 3809, 1895, ..., 2229, 2230,    0],
       [4802, 1594, 1596, ..., 3204, 3205,    0],
       [4802, 4710, 4521, ..., 3140, 3141,    0]], dtype=int64)

* np.sort(), np.argsort()

In [59]:
a = np.array([11, 10, 13, 12])
np.sort(a)

array([10, 11, 12, 13])

In [61]:
np.argsort(a)

array([1, 0, 3, 2], dtype=int64)

In [63]:
a[[1, 0, 3, 2]]

array([10, 11, 12, 13])

In [62]:
np.argsort(a)[::-1]

array([2, 3, 0, 1], dtype=int64)

In [65]:
a[[2, 3, 0, 1]]

array([13, 12, 11, 10])

In [44]:
genre_sim_sorted_ind = np.argsort(genre_sim)[:, ::-1]
genre_sim_sorted_ind[:1]

array([[   0, 3494,  813, ..., 3038, 3037, 2401]], dtype=int64)

#### ③ 장르 콘텐츠 필터링을 이용한 영화 추천
장르 유사도에 따라 영화를 추천하는 함수 find_sim_movie() 생성

In [45]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    
    # 인자로 입력된 movies_df 에서 'title' 컬럼이 입력된 title_name 값인 DataFrame추출
    title_movie = df[df['title'] == title_name]
    
    # title_name을 가진 DataFrame의 index 객체를 ndarray로 반환하고 
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n 개의 index 추출
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]
    
    # 추출된 top_n index들 출력. top_n index는 2차원 데이터 임. 
    #dataframe에서 index로 사용하기 위해서 1차원 array로 변경
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    
    return df.iloc[similar_indexes]

In [48]:
movies_df[:3]

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   

                                          genres  vote_average  vote_count  \
0  [Action, Adventure, Fantasy, Science Fiction]           7.2       11800   
1                   [Adventure, Fantasy, Action]           6.9        4500   
2                     [Action, Adventure, Crime]           6.3        4466   

   popularity                                           keywords  \
0  150.437577  [culture clash, future, space war, space colon...   
1  139.082615  [ocean, drug abuse, exotic island, east india ...   
2  107.376788  [spy, based on novel, secret agent, sequel, mi...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   

                             genres_literal  
0  Action Adventure Fantasy Science Fiction  
1                  Adventure Fantasy Action  
2                    Action Adventure Crime

In [50]:
movies_df[movies_df['title'] == 'Kids']

id title          genres  vote_average  vote_count  popularity  \
4217  9344  Kids  [Drama, Crime]           6.8         279   13.291991   

                   keywords  \
4217  [puberty, first time]   

                                               overview genres_literal  
4217  A controversial portrayal of teens in New York...    Drama Crime

In [51]:
find_sim_movie(movies_df, genre_sim_sorted_ind, 'The Godfather', 10)

[[2731 1243 3636 1946 2640 4065 1847 4217  883 3866]]


id                                           title          genres  \
2731     240                          The Godfather: Part II  [Drama, Crime]   
1243     203                                    Mean Streets  [Drama, Crime]   
3636   36351                                   Light Sleeper  [Drama, Crime]   
1946   11699  The Bad Lieutenant: Port of Call - New Orleans  [Drama, Crime]   
2640     400         Things to Do in Denver When You're Dead  [Drama, Crime]   
4065  364083                                      Mi America  [Drama, Crime]   
1847     769                                      GoodFellas  [Drama, Crime]   
4217    9344                                            Kids  [Drama, Crime]   
883      640                             Catch Me If You Can  [Drama, Crime]   
3866     598                                     City of God  [Drama, Crime]   

      vote_average  vote_count  popularity  \
2731           8.3        3338  105.792936   
1243           7.2         345   17.002096   
3636           5.7          15    6.063868   
1946           6.0         326   17.339852   
2640           6.7          85    6.932221   
4065           0.0           0    0.039007   
1847           8.2        3128   63.654244   
4217           6.8         279   13.291991   
883            7.7        3795   73.944049   
3866           8.1        1814   44.356711   

                                               keywords  \
2731  [italo-american, cuba, vororte, melancholy, pr...   
1243  [epilepsy, protection money, secret love, mone...   
3636  [suicide, drug dealer, redemption, addict, exi...   
1946  [police brutality, organized crime, policeman,...   
2640  [father son relationship, bounty hunter, boat,...   
4065                       [new york state, hate crime]   
1847  [prison, based on novel, florida, 1970s, mass ...   
4217                              [puberty, first time]   
883   [con man, biography, fbi agent, overhead camer...   
3866  [male nudity, street gang, brazilian, photogra...   

                                               overview genres_literal  
2731  In the continuing saga of the Corleone crime f...    Drama Crime  
1243  A small-time hood must choose from among love,...    Drama Crime  
3636  A drug dealer with upscale clientele is having...    Drama Crime  
1946  Terrence McDonagh, a New Orleans Police sergea...    Drama Crime  
2640  A mafia film in Tarantino style with a star-st...    Drama Crime  
4065  A hate-crime has been committed in a the small...    Drama Crime  
1847  The true story of Henry Hill, a half-Irish, ha...    Drama Crime  
4217  A controversial portrayal of teens in New York...    Drama Crime  
883   A true story about Frank Abagnale Jr. who, bef...    Drama Crime  
3866  Cidade de Deus is a shantytown that started du...    Drama Crime

In [52]:
#영화 평점 정보 확인
movies_df[['title', 'vote_average', 'vote_count']].sort_values('vote_average', ascending=False)[:10]

title  vote_average  vote_count
3519          Stiff Upper Lips          10.0           1
4247     Me You and Five Bucks          10.0           2
4045     Dancer, Texas Pop. 81          10.0           1
4662            Little Big Top          10.0           1
3992                 Sardaarji           9.5           2
2386            One Man's Hero           9.3           2
2970        There Goes My Baby           8.5           2
1881  The Shawshank Redemption           8.5        8205
2796     The Prisoner of Zenda           8.4          11
3337             The Godfather           8.4        5893

* 가중 평점<br>
(v / (v+m)) * R + (m / (v+m)) * C<br>

v : 개별 영화에 평점을 투표한 횟수<br>
m : 평점을 부여하기 위한 최소 투표 횟수<br>
R : 개별 영화에 대한 평균 평점<br>
C : 전체 영화에 대한 평균 평점

In [54]:
#평점에 평가 횟수를 반영하는 새로운 평가 방식 -> 가중평점 사용
C = movies_df['vote_average'].mean()
m = movies_df['vote_count'].quantile(0.6)
print(C, m)

6.092171559442011 370.1999999999998


* 기존 평점을 새로운 가중 평점으로 변경하는 함수 weighted_vote_average() 생성<br>
새로운 평점 정보 : 'vote_weighted'

In [55]:
def weighted_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']
    
    return ( (v / (v+m)) * R ) + ( (m / (v+m)) * C )

In [ ]:
#movies_df['vote_count'].replace(0,1)
#movies_df['vote_average'].replace(0,1)

In [56]:
movies_df.apply(weighted_vote_average, axis=1)

0       7.166301
1       6.838594
2       6.284091
3       7.541095
4       6.098838
          ...   
4798    6.290894
4799    6.089611
4800    6.106650
4801    6.084894
4802    6.100782
Length: 4803, dtype: float64

In [57]:
movies_df['weighted_vote'] = movies_df.apply(weighted_vote_average, axis=1)

movies_df[['title', 'vote_average', 'weighted_vote', 'vote_count']].sort_values(
           'weighted_vote', ascending=False)[:10]

title  vote_average  weighted_vote  vote_count
1881  The Shawshank Redemption           8.5       8.396052        8205
3337             The Godfather           8.4       8.263591        5893
662                 Fight Club           8.3       8.216455        9413
3232              Pulp Fiction           8.3       8.207102        8428
65             The Dark Knight           8.2       8.136930       12002
1818          Schindler's List           8.3       8.126069        4329
3865                  Whiplash           8.3       8.123248        4254
809               Forrest Gump           8.2       8.105954        7927
2294             Spirited Away           8.3       8.105867        3840
2731    The Godfather: Part II           8.3       8.079586        3338

* 새롭게 정의된 평점 기준에 따라 다시 영화 추천

In [58]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values
    
    # top_n의 2배에 해당하는 쟝르 유사성이 높은 index 추출 
    similar_indexes = sorted_ind[title_index, :(top_n*2)]
    similar_indexes = similar_indexes.reshape(-1)
    
    # 기준 영화 index는 제외
    similar_indexes = similar_indexes[similar_indexes != title_index]
    
    # top_n의 2배에 해당하는 후보군에서 weighted_vote 높은 순으로 top_n 만큼 추출 
    return df.iloc[similar_indexes].sort_values('weighted_vote', ascending=False)[:top_n]

similar_movies = find_sim_movie(movies_df, genre_sim_sorted_ind, 'The Godfather',10)
similar_movies[['title', 'vote_average', 'weighted_vote']]

title  vote_average  weighted_vote
2731       The Godfather: Part II           8.3       8.079586
1847                   GoodFellas           8.2       7.976937
3866                  City of God           8.1       7.759693
1663  Once Upon a Time in America           8.2       7.657811
883           Catch Me If You Can           7.7       7.557097
281             American Gangster           7.4       7.141396
4041              This Is England           7.4       6.739664
1149              American Hustle           6.8       6.717525
1243                 Mean Streets           7.2       6.626569
2839                     Rounders           6.9       6.530427

### (8) 파이썬 추천 시스템 패키지 - Surprise
Surprise는 사이킷런과 유사한 API를 지향하며, 간단한 API만을 이용해 파이썬 기반에서 추천 시스템을 구현해준다<br>
fit(), predict(), train_test_split(), cross_validate(), GridSearchCV 기능을 제공한다

#### ① Surprise를 이용한 시스템 구축

In [106]:
import surprise 
print(surprise.__version__)

1.1.1


In [107]:
from surprise import SVD
from surprise import Dataset
from surprise import accuracy
from surprise.model_selection import train_test_split

In [108]:
data = Dataset.load_builtin('ml-100k')

In [110]:
#학습, 데이터 세트로 분리
trainset, testset = train_test_split(data, test_size=.25, random_state=0)

In [111]:
#SVD로 잠재 요인 협업 필터링 수행
algo = SVD(random_state=0)
algo.fit(trainset)

In [115]:
#추천을 예측하는 메서드1 : test() 사용자-아이템 평점 데이터 세트 전체에 대해서 추천을 예측
predictions = algo.test(testset)

print('prediction type:', type(predictions), 'size:', len(predictions))
predictions[:5]

prediction type: <class 'list'> size: 25000


[Prediction(uid='120', iid='282', r_ui=4.0, est=3.5114147666251547, details={'was_impossible': False}),
 Prediction(uid='882', iid='291', r_ui=4.0, est=3.573872419581491, details={'was_impossible': False}),
 Prediction(uid='535', iid='507', r_ui=5.0, est=4.033583485472447, details={'was_impossible': False}),
 Prediction(uid='697', iid='244', r_ui=5.0, est=3.8463639495936905, details={'was_impossible': False}),
 Prediction(uid='751', iid='385', r_ui=4.0, est=3.1807542478219157, details={'was_impossible': False})]

In [114]:
#uid : 사용자 아이디, iid : 아이템 아이디, est : 추천 예측 평점 (r_ui : 실제 평점)
[ (pred.uid, pred.iid, pred.est) for pred in predictions ]
[ (pred.uid, pred.iid, pred.est) for pred in predictions[:3] ]

[('120', '282', 3.5114147666251547),
 ('882', '291', 3.573872419581491),
 ('535', '507', 4.033583485472447)]

In [116]:
#추천을 예측하는 메서드2 : predict() 개별 사용자의 아이템에 대한 추천 평점 예측
#사용자 아이디, 아이템 아이디는 문자열로 입력
uid = str(196)
iid = str(302)
pred = algo.predict(uid, iid)
pred

Prediction(uid='196', iid='302', r_ui=None, est=4.494386477040736, details={'was_impossible': False})

In [117]:
#테스트 데이터 세트를 통해 추천 예측 평점과 실제 평점과의 차이 평가
accuracy.rmse(predictions)

RMSE: 0.9467


0.9466860806937948

#### * Surprise 주요 모듈
Dataset.load_builtin(name= 'ml_100k') : 무비렌즈 아카이브 FTP 서비스에서 무비렌즈 데이터를 내려 받는다<br>
Dataset.load_from_file(file_path, reader) : OS 파일에서 데이터를 로딩할 때 사용<br>
Dataset.load_from_df(df, reader) : 판다스의 DataFrame 에서 데이터를 로딩

* OS 파일 데이터를 Surprise 데이터 세트로 로딩

In [120]:
ratings = pd.read_csv('ratings.csv')
ratings[:5]

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [121]:
ratings.to_csv('./ratings_noh.csv', index=False, header=False)

In [122]:
from surprise import Reader

Surprise 데이터 세트는 기본적으로 무비렌즈 데이터 형식을 따르므로, 무비렌즈 데이터 형식이 아닌 다른 OS 파일의 경우 Reader 클래스를 먼저 설정해야 한다<br>

* Reader 클래스의 주요 생성 파라미터<br>
line_format (string) : 칼럼을 순서대로 나열, 입력된 문자열을 공백을 기준으로 분리해 칼럼으로 인식한다<br>
sep (char) : 칼럼을 분리하는 분리자, 디폴트는 '\t'<br>
rating_scale (tuple, optional) : 평점 값의 최소 ~ 최대 평점을 설정 (디폴트는 (1, 5))

In [125]:
reader = Reader(line_format = 'user item rating timestamp', sep=',', rating_scale=(0.5, 5))
data = Dataset.load_from_file('./ratings_noh.csv', reader=reader)
data

In [126]:
#SVD 행렬 분해 기법을 이용해 추천 예측
trainset, testset = train_test_split(data, test_size=.25, random_state=0)

algo = SVD(n_factors=50, random_state=0)

#학습 데이터로 학습, 테스트 데이터 세트로 평점 예측 후 평가
algo.fit(trainset)
predictions = algo.test(testset)
accuracy.rmse(predictions)

RMSE: 0.8682


0.8681952927143516

* 판다스 DataFrame에서 Surprise 데이터 세트로 로딩<br>
Dataset.load_form_df() 를 이용하면 판다스의 DataFrame 에서도 Surprise 데이터 세트로 로딩할 수 있다

In [127]:
import pandas as pd
from surprise import Reader, Dataset

In [128]:
ratings = pd.read_csv('ratings.csv')
reader = Reader(rating_scale=(0.5, 5.0))

In [129]:
#ratings DataFrame 에서 칼럼은 (사용자 아이디, 아이템 아이디, 평점 순서) 를 지켜야 한다
data = Dataset.load_from_df(ratings[['userId', 'movieId', 'rating']], reader)
trainset, testset = train_test_split(data, test_size=.25, random_state=0)

In [130]:
algo = SVD(n_factors=50, random_state=0)
algo.fit(trainset)
predictions = algo.test(testset)
accuracy.rmse(predictions)

RMSE: 0.8682


0.8681952927143516

* Surprise 추천 알고리즘 클래스<br>
SVD : 행렬 분해를 통한 잠재 요인 협업 필터링을 위한 알고리즘<br>
SVD(n_factors = 잠재 요인 k의 개수, n_epochs = SGD 수행시 반복 횟수, biased=True)<br>

* 베이스라인 평점<br>
개인의 성향에 따라 아이템 평가에 편향성(bias) 요소를 반영하여 평점을 부과하는 것<br>
보통 (전체 평균 평점 + 사용자 편향 점수 + 아이템 편향 점수) 로 계산된다

#### * 교차 검증과 하이퍼 파라미터 튜닝
Surprise는 교차 검증과 하이퍼 파라미터 튜닝을 위해 사이킷런과 유사한 cross_validate() 와 GridSearchCV 클래스를 제공한다

In [131]:
from surprise.model_selection import cross_validate

In [133]:
#판다스 DataFrame에서 Surprise 데이터 세트로 데이터 로딩
ratings = pd.read_csv('ratings.csv')
reader = Reader(rating_scale=(0.5, 5.0))
data = Dataset.load_from_df(ratings[['userId', 'movieId', 'rating']], reader)

algo = SVD(random_state=0)
cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.8764  0.8644  0.8817  0.8761  0.8727  0.8742  0.0057  
MAE (testset)     0.6712  0.6636  0.6771  0.6734  0.6741  0.6719  0.0046  
Fit time          4.23    4.23    4.37    4.26    4.24    4.27    0.05    
Test time         0.12    0.38    0.11    0.11    0.11    0.17    0.10    


{'test_rmse': array([0.87636239, 0.86439018, 0.88167439, 0.87607045, 0.8726666 ]),
 'test_mae': array([0.67117809, 0.66357401, 0.67712209, 0.6734285 , 0.67410065]),
 'fit_time': (4.225306034088135,
  4.234225749969482,
  4.3728320598602295,
  4.259190797805786,
  4.236243486404419),
 'test_time': (0.12394356727600098,
  0.37545204162597656,
  0.11288762092590332,
  0.1077125072479248,
  0.11198306083679199)}

In [134]:
from surprise.model_selection import GridSearchCV

In [135]:
params = {'n_epochs' : [20,40,60], 'n_factors' : [50,100,200]}

gs = GridSearchCV(SVD, params, measures=['rmse', 'mae'], cv=3)
gs.fit(data)

print(gs.best_score['rmse'])
print(gs.best_params['rmse'])

0.8770648132276181
{'n_epochs': 20, 'n_factors': 50}


#### * Surprise 를 이용한 개인화 영화 추천 시스템 구축
Surprise 패키지로 학습된 추천 알고리즘을 기반으로 특정 사용자가 아직 평점을 매기지 않은 (관람하지 않은) 영화 중에서 개인 취향에 가장 적절한 영화를 추천해보자

데이터 세트 전체를 학습 데이터로 사용하기 위해 DatasetAutoFolds 클래스를 이용한다<br>
DatasetAutoFolds 객체의 build_full_trainset() 메서드를 호출하여 전체 데이터 세트를 학습 데이터로 사용한다

In [136]:
from surprise.dataset import DatasetAutoFolds

In [137]:
reader = Reader(line_format = 'user item rating timestamp', sep=',', rating_scale=(0.5, 5))

#DatasetAutoFolds 클래스를 ratings_noh.csv 파일 기반으로 생성
data_folds = DatasetAutoFolds(ratings_file='ratings_noh.csv', reader= reader)

#전체 데이터를 학습 데이터로 생성
trainset = data_folds.build_full_trainset()

In [138]:
#SVD를 이용해 학습 수행
algo = SVD(n_epochs=20, n_factors=50, random_state=0)
algo.fit(trainset)

In [142]:
#영화에 대한 상세 속성 정보 DataFrame 로딩
movies = pd.read_csv('./ml-latest-small/ml-latest-small/movies.csv')
movies

movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Drama|Romance  
4                                          Comedy  
...                                           ...  
9737              Action|Animation|Comedy|Fantasy  
9738                     Animation|Comedy|Fantasy  
9739                                        Drama  
9740                             Action|Animation  
9741                                       Comedy  

[9742 rows x 3 columns]

In [146]:
#임의로 지정한 특정 사용자(userId=9), userId=9가 아직 평점을 매기지 않은 영화 movieId=24
movieIds = ratings[ratings['userId']==9]['movieId']
print(movieIds)

if movieIds[movieIds==42].count() == 0:
    print('userId=9 는 movieId=24 의 평점이 없음')
    
print(movies[movies['movieId'] == 42])

1073      41
1074     187
1075     223
1076     371
1077     627
1078     922
1079     923
1080    1037
1081    1095
1082    1198
1083    1270
1084    1674
1085    1987
1086    2011
1087    2012
1088    2023
1089    2300
1090    2877
1091    2901
1092    3173
1093    3328
1094    3735
1095    4131
1096    4558
1097    4993
1098    5218
1099    5378
1100    5445
1101    5447
1102    5451
1103    5481
1104    5507
1105    5841
1106    5843
1107    5872
1108    5890
1109    5891
1110    5893
1111    5902
1112    5952
1113    5956
1114    5962
1115    5965
1116    5988
1117    6001
1118    6044
Name: movieId, dtype: int64
userId=9 는 movieId=24 의 평점이 없음
    movieId                   title              genres
38       42  Dead Presidents (1995)  Action|Crime|Drama


In [149]:
#movieId=24 에 대한 userId=9 의 추천 예상 평점 확인 (est 값)
uid = "9"
iid = "42"
pred = algo.predict(uid, iid, verbose=True)

user: 9          item: 42         r_ui = None   est = 3.13   {'was_impossible': False}


In [150]:
#사용자가 평점을 매기지 않은 전체 영화에 대한 예측 평점
def get_unseen_surprise(ratings, movies, userId):
    #입력값으로 들어온 userId에 해당하는 사용자가 평점을 매긴 모든 영화 리스트
    seen_movies = ratings[ratings['userId'] == userId]['movieId'].tolist()
    
    #모든 영화의 movieId 리스트
    total_movieIds = movies['movieId'].tolist()
    
    #모든 영화의 movieId 중 이미 평점을 매긴 영화의 movieId는 제외
    #unseen_movies = [movie for movie in total_movieIds if movie not in seen_movies]
    unseen_movies = []
    for movie in total_movieIds:
        if movie not in seen_movies:
            unseen_movies.append(movie)
            
    print('전체 영화 수:', len(total_movieIds), '평점 매긴 영화 수:', len(seen_movies),
          '추천 대상 영화 수:', len(unseen_movies))
    
    return unseen_movies

In [151]:
unseen_movies = get_unseen_surprise(ratings, movies, 9)

전체 영화 수: 9742 평점 매긴 영화 수: 46 추천 대상 영화 수: 9696


In [152]:
#SVD를 이용해 높은 예측 평점을 가진 순으로 영화 추천
def recomm_movie_by_surprise(algo, userId, unseen_movies, top_n=10):
    
    #알고리즘 객체의 predict() 메서드를 평점이 없는 영화에 반복 수행
    predictions = [algo.predict(str(userId), str(movieId)) for movieId in unseen_movies]
    
    #predictions list 객체는 surprise의 Predictions 객체를 원소로 갖고 있다
    # [Prediction(uid='9', iid='1', est=3.69), Prediction(uid='9', iid='2', est=2.98),,,,]
    
    #predictions list 객체를 est 값으로 정렬
    def sortkey_est(pred):
        return pred.est
    
    predictions.sort(key=sortkey_est, reverse=True)
    top_predictions = predictions[:top_n]
    
    #top_n으로 추출된 영화의 정보 추출
    top_movie_ids = [int(pred.iid) for pred in top_predictions]
    top_movie_titles = movies[movies.movieId.isin(top_movie_ids)]['title']
    top_movie_rating = [pred.est for pred in top_predictions]
    
    top_movie_preds = [(id, title, rating) for id, title, rating in \
                      zip(top_movie_ids, top_movie_titles, top_movie_rating)]
    
    return top_movie_preds

In [153]:
unseen_movies = get_unseen_surprise(ratings, movies, 9)
top_movie_preds = recomm_movie_by_surprise(algo, 9, unseen_movies, top_n=10)
print('##### Top-10 추전 영화 리스트 #####')

for top_movie in top_movie_preds:
    print(top_movie[1], ":", top_movie[2])

전체 영화 수: 9742 평점 매긴 영화 수: 46 추천 대상 영화 수: 9696
##### Top-10 추전 영화 리스트 #####
Usual Suspects, The (1995) : 4.306302135700814
Star Wars: Episode IV - A New Hope (1977) : 4.281663842987387
Pulp Fiction (1994) : 4.278152632122759
Silence of the Lambs, The (1991) : 4.226073566460876
Godfather, The (1972) : 4.1918097904381995
Streetcar Named Desire, A (1951) : 4.154746591122658
Star Wars: Episode V - The Empire Strikes Back (1980) : 4.122016128534504
Star Wars: Episode VI - Return of the Jedi (1983) : 4.108009609093436
Goodfellas (1990) : 4.083464936588478
Glory (1989) : 4.07887165526957


## 크롤링 (1)

In [85]:
from urllib import request
from bs4 import BeautifulSoup

In [88]:
url = "https://search.naver.com/search.naver?where=news&sm=tab_jum&query=%EC%9A%B0%ED%81%AC%EB%9D%BC%EC%9D%B4%EB%82%98"

html = request.urlopen(url).read()
html

b'<!doctype html> <html lang="ko"> <head> <meta charset="utf-8"> <meta name="referrer" content="always">  <meta name="format-detection" content="telephone=no,address=no,email=no"> <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=2.0"> <meta property="og:title" content="\xec\x9a\xb0\xed\x81\xac\xeb\x9d\xbc\xec\x9d\xb4\xeb\x82\x98 : \xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84 \xeb\x89\xb4\xec\x8a\xa4\xea\xb2\x80\xec\x83\x89"/> <meta property="og:image" content="https://ssl.pstatic.net/sstatic/search/common/og_v3.png"> <meta property="og:description" content="\'\xec\x9a\xb0\xed\x81\xac\xeb\x9d\xbc\xec\x9d\xb4\xeb\x82\x98\'\xec\x9d\x98 \xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84 \xeb\x89\xb4\xec\x8a\xa4\xea\xb2\x80\xec\x83\x89 \xea\xb2\xb0\xea\xb3\xbc\xec\x9e\x85\xeb\x8b\x88\xeb\x8b\xa4."> <meta name="description" lang="ko" content="\'\xec\x9a\xb0\xed\x81\xac\xeb\x9d\xbc\xec\x9d\xb4\xeb\x82\x98\'\xec\x9d\x98 \xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84 \xeb\x89\xb4\xec\x8a\xa4\x

In [89]:
BeautifulSoup(html, 'html.parser')    #'html.parser' : 해석기

<!DOCTYPE html>
 <html lang="ko"> <head> <meta charset="utf-8"/> <meta content="always" name="referrer"/> <meta content="telephone=no,address=no,email=no" name="format-detection"/> <meta content="width=device-width,initial-scale=1.0,maximum-scale=2.0" name="viewport"/> <meta content="우크라이나 : 네이버 뉴스검색" property="og:title"> <meta content="https://ssl.pstatic.net/sstatic/search/common/og_v3.png" property="og:image"/> <meta content="'우크라이나'의 네이버 뉴스검색 결과입니다." property="og:description"/> <meta content="'우크라이나'의 네이버 뉴스검색 결과입니다." lang="ko" name="description"/> <title>우크라이나 : 네이버 뉴스검색</title> <link href="https://ssl.pstatic.net/sstatic/search/favicon/favicon_191118_pc.ico" rel="shortcut icon"/> <link href="https://ssl.pstatic.net/sstatic/search/opensearch-description.https.xml" rel="search" title="Naver" type="application/opensearchdescription+xml"><link href="https://ssl.pstatic.net/sstatic/search/pc/css/search1_221006.css" rel="stylesheet" type="text/css"/> <link href="https://ssl.pstatic.net

#### * 뉴스 기사의 제목만 10개 추출

In [91]:
#제목 10개만 추출
soup = BeautifulSoup(html, 'html.parser')
soup.find_all('title')

[<title>우크라이나 : 네이버 뉴스검색</title>]

In [93]:
soup.find(class_ = "news_tit")    #한개만
#soup.find_all(class_ = "news_tit")

<a class="news_tit" href="http://www.fnnews.com/news/202210260901472893" onclick="return goOtherCR(this, 'a=nws*e.tit&amp;r=1&amp;i=880000FF_000000000000000004918400&amp;g=014.0004918400&amp;u='+urlencode(this.href));" target="_blank" title="EU, '500조 투입' 우크라이나 재건 '마셜 플랜' 촉구">EU, '500조 투입' <mark>우크라이나</mark> 재건 '마셜 플랜' 촉구</a>

In [94]:
news_tit = soup.find_all(class_ = "news_tit")
len(news_tit)

10

In [95]:
news_tit[0]

<a class="news_tit" href="http://www.fnnews.com/news/202210260901472893" onclick="return goOtherCR(this, 'a=nws*e.tit&amp;r=1&amp;i=880000FF_000000000000000004918400&amp;g=014.0004918400&amp;u='+urlencode(this.href));" target="_blank" title="EU, '500조 투입' 우크라이나 재건 '마셜 플랜' 촉구">EU, '500조 투입' <mark>우크라이나</mark> 재건 '마셜 플랜' 촉구</a>

In [96]:
news_tit[0].text

"EU, '500조 투입' 우크라이나 재건 '마셜 플랜' 촉구"

In [101]:
for i in range(len(news_tit)):
    print(news_tit[i].text)

EU, '500조 투입' 우크라이나 재건 '마셜 플랜' 촉구
우크라이나, 수백만 해외 피란민에 “올겨울엔 귀국 말라” 당부
악수하는 독일-우크라이나 대통령
“감당할 수 없다, 귀국하지 마라”...혹독한 겨울 대비 나선 우크라이나
인도 정부, 우크라이나 체류 자국민에 “즉시 떠나라” 거듭 촉구
미니 핵폭탄 '더티밤' 논란…우크라이나 전쟁 변수로?
숄츠 獨총리, 우크라이나 재건회의서 광범위한 지원 약속
[이 시각 세계] '우크라이나 재건' EU 주요 7개국 회의
우크라이나 헤르손, 수복이냐 물바다냐 갈림길
러시아, 우크라이나의 '더티밤' 사용 경고...서방, "거짓 깃발 작전"


In [102]:
[news_tit[i].text for i in range(len(news_tit))]

["EU, '500조 투입' 우크라이나 재건 '마셜 플랜' 촉구",
 '우크라이나, 수백만 해외 피란민에 “올겨울엔 귀국 말라” 당부',
 '악수하는 독일-우크라이나 대통령',
 '“감당할 수 없다, 귀국하지 마라”...혹독한 겨울 대비 나선 우크라이나',
 '인도 정부, 우크라이나 체류 자국민에 “즉시 떠나라” 거듭 촉구',
 "미니 핵폭탄 '더티밤' 논란…우크라이나 전쟁 변수로?",
 '숄츠 獨총리, 우크라이나 재건회의서 광범위한 지원 약속',
 "[이 시각 세계] '우크라이나 재건' EU 주요 7개국 회의",
 '우크라이나 헤르손, 수복이냐 물바다냐 갈림길',
 '러시아, 우크라이나의 \'더티밤\' 사용 경고...서방, "거짓 깃발 작전"']

In [103]:
news_tit[0].attrs['href']

'http://www.fnnews.com/news/202210260901472893'

In [104]:
[news_tit[i].attrs['href'] for i in range(len(news_tit))]

['http://www.fnnews.com/news/202210260901472893',
 'https://news.kbs.co.kr/news/view.do?ncd=5587218&ref=A',
 'http://www.newsis.com/view/?id=NISI20221026_0001114670',
 'https://www.khan.co.kr/world/europe-russia/article/202210261512001',
 'https://news.kbs.co.kr/news/view.do?ncd=5587258&ref=A',
 'http://www.yonhapnewstv.co.kr/MYH20221025008300032/?input=1825m',
 'http://www.newsis.com/view/?id=NISX20221025_0002059764&cID=10101&pID=10100',
 'https://imnews.imbc.com/replay/2022/nwtoday/article/6420657_35752.html',
 'https://news.kmib.co.kr/article/view.asp?arcid=0924270141&code=11141500&cp=nv',
 'http://www.womennews.co.kr/news/articleView.html?idxno=229161']

In [105]:
for i in range(len(news_tit)):
    print(news_tit[i].text, ':', news_tit[i].attrs['href'])

EU, '500조 투입' 우크라이나 재건 '마셜 플랜' 촉구 : http://www.fnnews.com/news/202210260901472893
우크라이나, 수백만 해외 피란민에 “올겨울엔 귀국 말라” 당부 : https://news.kbs.co.kr/news/view.do?ncd=5587218&ref=A
악수하는 독일-우크라이나 대통령 : http://www.newsis.com/view/?id=NISI20221026_0001114670
“감당할 수 없다, 귀국하지 마라”...혹독한 겨울 대비 나선 우크라이나 : https://www.khan.co.kr/world/europe-russia/article/202210261512001
인도 정부, 우크라이나 체류 자국민에 “즉시 떠나라” 거듭 촉구 : https://news.kbs.co.kr/news/view.do?ncd=5587258&ref=A
미니 핵폭탄 '더티밤' 논란…우크라이나 전쟁 변수로? : http://www.yonhapnewstv.co.kr/MYH20221025008300032/?input=1825m
숄츠 獨총리, 우크라이나 재건회의서 광범위한 지원 약속 : http://www.newsis.com/view/?id=NISX20221025_0002059764&cID=10101&pID=10100
[이 시각 세계] '우크라이나 재건' EU 주요 7개국 회의 : https://imnews.imbc.com/replay/2022/nwtoday/article/6420657_35752.html
우크라이나 헤르손, 수복이냐 물바다냐 갈림길 : https://news.kmib.co.kr/article/view.asp?arcid=0924270141&code=11141500&cp=nv
러시아, 우크라이나의 '더티밤' 사용 경고...서방, "거짓 깃발 작전" : http://www.womennews.co.kr/news/articleView.html?idxno=229161
